export interface AuthAccessPayload {
  id: number;
  username: string;
}

export interface AuthRefreshPayload {
  id: number;
}

export interface ServiceHealthCheck {
  enabled: boolean;
  type?: 'http';
  url?: string;
  interval?: number;
  timeout?: number;
}

export interface ServiceExposureEnvKeys {
  // Compose env var(s) that should receive the service's public URL, scheme
  // included — `https://<host>` (e.g. PAPERLESS_URL, BOOKSTACK_URL).
  url?: string[];
  // Compose env var(s) that should receive the bare public hostname, no
  // scheme (e.g. N8N_HOST, NEXTCLOUD_OVERWRITEHOST).
  host?: string[];
  // Compose env var(s) holding a separated allowed-hosts list that the public
  // hostname must be appended to (e.g. PAPERLESS_ALLOWED_HOSTS,
  // NEXTCLOUD_TRUSTED_DOMAINS).
  allowedHosts?: string[];
  // Separator for the `allowedHosts` lists. Defaults to ",". Nextcloud's
  // NEXTCLOUD_TRUSTED_DOMAINS is space-separated, so it sets " ".
  allowedHostsSeparator?: string;
  // Literal env values to set only while exposure is enabled — for reverse
  // proxy knobs that aren't derived from the hostname, e.g.
  // { N8N_PROTOCOL: 'https' }, { NEXTCLOUD_OVERWRITEPROTOCOL: 'https' }.
  staticOnExposure?: Record<string, string>;
}

// Marks a service that needs a config *file* touched (not just env) before it
// will accept proxied requests once exposed — see services/exposureConfigFiles.ts.
// Currently only Home Assistant (its http: block).

export interface ServiceSetupToken {
  // Regex with one capture group, applied to the container's full logs, to
  // pull out a one-time first-run setup token/password some images print
  // (e.g. Portainer's `setup_token=<value>`).
  logPattern: string;
}

export interface ServiceAdditionalExposure {
  // Appended to the base hostname: <service>-<suffix>.<base-domain>.
  suffix: string;
  // Shown in the dashboard UI (exposure status, audit logs).
  label: string;
  // The compose ${VAR} name whose published host port this hostname should
  // forward to — required because a multi-container app publishes more than
  // one port, so "first port in the file" (the single-hostname default)
  // can't tell them apart. See getPublishedUpstreamPort.
  portEnvVar: string;
  // True if this upstream serves real gRPC (not grpc-web) alongside its REST
  // API on the same port — native clients need HTTP/2 end-to-end, which
  // plain proxy_pass doesn't provide. See buildGrpcAdvancedConfig in
  // npmClient.ts. Defaults to false (plain HTTP/1.1 proxying).
  grpc?: boolean;
}

// Groups services on the dashboard so the grid reads by function instead of
// as one flat list of 25+ cards.
export type ServiceCategory =
  | 'Networking & Security'
  | 'Monitoring & Management'
  | 'Media'
  | 'Backup & Storage'
  | 'Productivity'
  | 'Home Automation'
  | 'Development';

export interface ServiceMailEnvKeys {
  smtpHost?: string[];
  smtpPort?: string[];
  smtpUser?: string[];
  smtpPassword?: string[];
  /** Receives 'tls' | 'ssl' | 'none' as-is. */
  smtpEncryption?: string[];
  /**
   * Translate the encryption value before setting `smtpEncryption` keys.
   * Apps disagree on the vocabulary — Vaultwarden wants
   * starttls/force_tls/off, others want tls/ssl/none or true/false — and
   * passing our name through verbatim silently misconfigures them: the app
   * usually falls back to "no encryption" rather than erroring.
   */
  smtpEncryptionMap?: Partial<Record<'tls' | 'ssl' | 'none', string>>;
  /** Some apps want a boolean "use TLS" rather than a named scheme. */
  smtpTlsBoolean?: string[];
  fromAddress?: string[];
  fromName?: string[];
  imapHost?: string[];
  imapPort?: string[];
  imapUser?: string[];
  imapPassword?: string[];
  imapEncryption?: string[];
  /** Set verbatim whenever mail is configured — e.g. MAIL_ENABLED=true. */
  staticWhenConfigured?: Record<string, string>;
}

export interface ServiceDefinition {
  name: string;
  label: string;
  description: string;
  icon: string;
  category: ServiceCategory;
  composePath: string;
  healthCheck: ServiceHealthCheck;
  exposureEnvKeys?: ServiceExposureEnvKeys;
  // See services/exposureConfigFiles.ts — service needs a config file edited
  // on exposure, beyond env overrides.
  exposureConfigFile?: boolean;
  setupToken?: ServiceSetupToken;
  // Compose env var(s) holding a random secret the app needs but can't
  // default (e.g. Vikunja's VIKUNJA_JWT_SECRET). When one of these is still
  // unset, the dashboard's config panel pre-fills it with a freshly
  // generated value so the user just has to hit Save. See services/appEnv.ts.
  autoGeneratedSecrets?: string[];
  // Compose env var(s) that are a plain boolean — the dashboard's config
  // panel renders a true/false choice instead of a free-text field.
  booleanEnvKeys?: string[];
  // Compose env var(s) the dashboard fills with a freshly generated random
  // secret the first time the service's config is saved, and never displays
  // — for tokens the user should neither see nor choose (e.g. Vaultwarden's
  // ADMIN_TOKEN). Implies the `autoGeneratedSecrets` behavior plus hidden.
  hiddenGeneratedSecrets?: string[];
  // Compose env var(s) whose value the dashboard manages automatically and
  // shows read-only rather than as an editable field — currently the keys it
  // derives from the exposure hostname (e.g. Vaultwarden's DOMAIN, which has
  // to equal the public URL). The client never submits these.
  managedEnvKeys?: string[];
  // Whether this service exposes a manageable admin account from the
  // dashboard (currently only Authelia's file-based users_database.yml —
  // see services/autheliaUsers.ts).
  supportsAdminUserManagement?: boolean;
  // Other SERVICES keys (separate compose projects) that must already be
  // running before this one can start — e.g. an app that authenticates
  // against Authelia's OIDC provider needs Authelia up first.
  dependsOn?: string[];
  // The host port this service listens on when it runs with
  // `network_mode: host` (currently Home Assistant, which needs host
  // networking for its zeroconf/SSDP/DHCP discovery). Such a service
  // publishes nothing — its compose file has no `ports:` mapping for
  // getPublishedUpstreamPort to read — but it is still reachable on the host
  // at a fixed port, so declaring it here keeps exposure, the health check
  // and the dashboard's "Open" link working. Unset for every bridged service,
  // where the compose file remains the source of truth.
  hostNetworkPort?: number;
  // Disambiguates which published port is the primary exposure's upstream,
  // for services whose compose file publishes more than one port where the
  // web UI isn't simply the first one listed — e.g. Pi-hole publishes DNS
  // (53/tcp, 53/udp) before its web port, so "first port in the file" (the
  // default getPublishedUpstreamPort behavior — see its docstring) would
  // pick DNS instead. Unset for every service with just one published port.
  exposurePortEnvVar?: string;
  // This service runs a database that must be dumped before its files are
  // backed up — copying a live Postgres or MariaDB data directory can restore
  // torn. Only the engine and the compose service name are declared:
  // credentials are read from the running container, so a password rotated in
  // the dashboard cannot leave a stale copy here. See services/appDumps.ts.
  //
  // SQLite apps need no declaration — they are discovered by file header.
  backup?: {
    engine: 'postgres' | 'mariadb' | 'mysql';
    /** Compose service name of the database container, e.g. 'itflow-db'. */
    service: string;
  };
  // Which of this service's env vars receive the global mail settings (see
  // services/mailEnv.ts). Declaring them here means SMTP/IMAP credentials are
  // configured once in the dashboard instead of pasted into every app that
  // sends email — and rotating the mailbox password is a single edit.
  mailEnvKeys?: ServiceMailEnvKeys;
  // Public subdomain to expose this service under, when it should differ
  // from the service's own key. The service name is an internal identity
  // (compose project, app directory, registry key); the hostname is a UX
  // decision, and the two shouldn't be forced to match. e.g. the browser
  // terminal is implemented with wetty but lives at ssh.<base-domain>,
  // because that is what a person looks for. Applies to the primary hostname
  // and is the stem for any additionalExposures. Unset = use the service name.
  exposureSubdomain?: string;
  // Secondary public hostnames this service needs beyond its primary one —
  // e.g. NetBird VPN's dashboard is a static SPA with no server-side proxy,
  // so its management API needs its own directly-reachable hostname.
  // Provisioned/torn down automatically alongside the primary exposure.
  additionalExposures?: ServiceAdditionalExposure[];
  // URL path where the app's web UI actually lives, when it isn't the bare
  // root — appended to the public URL for the dashboard "open" link (and any
  // future exposure health check). e.g. Pi-hole serves its admin UI under
  // `/admin`, so its bare hostname just 403s / redirects. Leading slash, no
  // trailing slash; unset for the common "UI is at /" case.
  webPath?: string;
}

export type ServiceState = 'running' | 'stopped' | 'starting' | 'error' | 'unknown';

// A container's published host port, read live from `docker ps` rather than
// parsed from the compose file — so it reflects what's actually bound right
// now and covers every container in a multi-container project.
export interface ServicePortMapping {
  hostPort: string;
  containerPort: string;
  protocol: string;
}

export interface ServiceStatusPayload {
  name: string;
  label?: string;
  description?: string;
  icon?: string;
  category?: ServiceCategory;
  state: ServiceState;
  healthy: boolean;
  lastChecked?: Date;
  error?: string;
  setupTokenSupported?: boolean;
  adminUserManagementSupported?: boolean;
  dependsOn?: string[];
  ports?: ServicePortMapping[];
  // The service's public hostname, only when exposure is enabled and
  // provisioned successfully — null/absent otherwise, including for
  // services with no published port to expose in the first place.
  exposedHostname?: string | null;
  // URL path suffix for the app's web UI when it isn't at the bare root
  // (e.g. Pi-hole's `/admin`) — the dashboard appends it to the "open" link.
  webPath?: string;
  // Published host port of the app's web UI (the exposurePortEnvVar one when
  // set — e.g. NPM's admin :81, not its proxy :80), while running. Lets the
  // dashboard offer a LAN link even when the app isn't publicly exposed.
  webPort?: number | null;
}

export interface ServiceStatusSummary {
  total: number;
  running: number;
  stopped: number;
  error: number;
  starting: number;
}

export interface ServiceStatusResponse {
  timestamp: Date;
  services: ServiceStatusPayload[];
  summary: ServiceStatusSummary;
}

export interface ResolvedComposeFile {
  projectName: string;
  appDir: string;
  composeFile: string | null;
}

/** A thrown error shape used across route handlers for consistent HTTP responses. */
export interface HttpError {
  statusCode?: number;
  message: string;
  details?: unknown;
  code?: string;
  stderr?: string;
}

export interface ExposureGlobalConfig {
  baseDomain: string;
  npmApiUrl: string;
  npmEmail: string;
  npmPassword: string;
  cloudflareAccountId: string;
  cloudflareZoneId: string;
  cloudflareTunnelId: string;
  cloudflareApiToken: string;
}

export interface ServiceExposureRow {
  service_name: string;
  enabled: boolean;
  hostname: string | null;
  upstream_scheme: string;
  upstream_host: string | null;
  upstream_port: number | null;
  websocket: boolean;
  authelia_protected: boolean;
  npm_host_id: number | null;
  cf_hostname_id: string | null;
  status: string;
  last_error: string | null;
  updated_at: Date;
}

export interface ServiceExposureInput {
  enabled: boolean;
  autheliaProtected?: boolean;
}

export interface ExposureProvisionResult {
  attempted: boolean;
  success?: boolean;
  warning?: string;
  hostname?: string;
}
