import fs from 'fs';
import os from 'os';
import path from 'path';
import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import { getServiceEnvStatus } from './appEnv';

// 'vikunja' is a real registry entry with autoGeneratedSecrets:
// ['VIKUNJA_JWT_SECRET']. Point APPS_DIR at a temp root and write a compose
// file under <tmp>/vikunja/ so resolveComposeFile() finds it without
// depending on the checked-in fixtures under apps/.
describe('getServiceEnvStatus — auto-generated secrets', () => {
  let tmpDir: string;
  let originalAppsDir: string | undefined;

  const compose = 'services:\n  app:\n    environment:\n      JWT: ${VIKUNJA_JWT_SECRET}\n      URL: ${VIKUNJA_PUBLIC_URL:-http://localhost:3456}\n';

  beforeEach(() => {
    tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'appenv-test-'));
    fs.mkdirSync(path.join(tmpDir, 'vikunja'));
    fs.writeFileSync(path.join(tmpDir, 'vikunja', 'compose.yaml'), compose);
    originalAppsDir = process.env.APPS_DIR;
    process.env.APPS_DIR = tmpDir;
  });

  afterEach(() => {
    fs.rmSync(tmpDir, { recursive: true, force: true });
    if (originalAppsDir === undefined) {
      delete process.env.APPS_DIR;
    } else {
      process.env.APPS_DIR = originalAppsDir;
    }
  });

  it('suggests a generated value for an unset auto-generated secret', async () => {
    const status = await getServiceEnvStatus('vikunja');
    const jwt = status?.fields.find((f) => f.key === 'VIKUNJA_JWT_SECRET');
    expect(jwt?.secret).toBe(true);
    expect(jwt?.isSet).toBe(false);
    expect(jwt?.suggestedValue).toMatch(/^[0-9a-f]{64}$/);
  });

  it('does not suggest a value once the secret is already set', async () => {
    fs.writeFileSync(path.join(tmpDir, 'vikunja', '.env'), 'VIKUNJA_JWT_SECRET=already-here\n');
    const status = await getServiceEnvStatus('vikunja');
    const jwt = status?.fields.find((f) => f.key === 'VIKUNJA_JWT_SECRET');
    expect(jwt?.isSet).toBe(true);
    expect(jwt?.suggestedValue).toBeNull();
  });

  it('never suggests a value for fields not in autoGeneratedSecrets', async () => {
    const status = await getServiceEnvStatus('vikunja');
    const url = status?.fields.find((f) => f.key === 'VIKUNJA_PUBLIC_URL');
    expect(url?.suggestedValue).toBeNull();
  });
});
