import fs from 'fs';
import os from 'os';
import path from 'path';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';

// The file logger appends to backend/logs/*.log; keep tests off the filesystem.
vi.mock('../utils/logger', () => ({
  default: { debug: vi.fn(), info: vi.fn(), warn: vi.fn(), error: vi.fn() },
}));
// loadStatus now consults exposure + the global timezone (both hit the DB).
vi.mock('./exposureEnv', () => ({ buildExposureEnvOverrides: vi.fn().mockResolvedValue({}) }));
vi.mock('../utils/generalSettings', () => ({ getAppTimezone: vi.fn().mockResolvedValue('Europe/Lisbon') }));

import { buildExposureEnvOverrides } from './exposureEnv';
import { ensureGeneratedSecrets, getServiceEnvStatus, saveServiceEnv } from './appEnv';

const mockedExposureOverrides = vi.mocked(buildExposureEnvOverrides);

// 'vikunja' is a real registry entry with autoGeneratedSecrets:
// ['VIKUNJA_JWT_SECRET']. Point APPS_DIR at a temp root and write a compose
// file under <tmp>/vikunja/ so resolveComposeFile() finds it without
// depending on the checked-in fixtures under apps/.
describe('getServiceEnvStatus — auto-generated secrets', () => {
  let tmpDir: string;
  let originalAppsDir: string | undefined;

  const compose = 'services:\n  app:\n    environment:\n      JWT: ${VIKUNJA_JWT_SECRET}\n      URL: ${VIKUNJA_PUBLIC_URL:-http://localhost:3456}\n';

  beforeEach(() => {
    tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'appenv-test-'));
    fs.mkdirSync(path.join(tmpDir, 'vikunja'));
    fs.writeFileSync(path.join(tmpDir, 'vikunja', 'compose.yaml'), compose);
    originalAppsDir = process.env.APPS_DIR;
    process.env.APPS_DIR = tmpDir;
  });

  afterEach(() => {
    fs.rmSync(tmpDir, { recursive: true, force: true });
    if (originalAppsDir === undefined) {
      delete process.env.APPS_DIR;
    } else {
      process.env.APPS_DIR = originalAppsDir;
    }
  });

  it('suggests a generated value for an unset auto-generated secret', async () => {
    const status = await getServiceEnvStatus('vikunja');
    const jwt = status?.fields.find((f) => f.key === 'VIKUNJA_JWT_SECRET');
    expect(jwt?.secret).toBe(true);
    expect(jwt?.isSet).toBe(false);
    expect(jwt?.suggestedValue).toMatch(/^[0-9a-f]{64}$/);
  });

  it('does not suggest a value once the secret is already set', async () => {
    fs.writeFileSync(path.join(tmpDir, 'vikunja', '.env'), 'VIKUNJA_JWT_SECRET=already-here\n');
    const status = await getServiceEnvStatus('vikunja');
    const jwt = status?.fields.find((f) => f.key === 'VIKUNJA_JWT_SECRET');
    expect(jwt?.isSet).toBe(true);
    expect(jwt?.suggestedValue).toBeNull();
  });

  it('never suggests a value for fields not in autoGeneratedSecrets', async () => {
    const status = await getServiceEnvStatus('vikunja');
    const url = status?.fields.find((f) => f.key === 'VIKUNJA_PUBLIC_URL');
    expect(url?.suggestedValue).toBeNull();
  });

  it('marks an exposureEnvKeys url field managed with the exposure value when exposure is on', async () => {
    mockedExposureOverrides.mockResolvedValueOnce({ VIKUNJA_PUBLIC_URL: 'https://vikunja.example.com' });
    const status = await getServiceEnvStatus('vikunja');
    const url = status?.fields.find((f) => f.key === 'VIKUNJA_PUBLIC_URL');
    expect(url?.managed).toBe(true);
    expect(url?.managedValue).toBe('https://vikunja.example.com');
  });
});

// TZ prefill + boolean auto-detection (no registry declaration needed).
describe('getServiceEnvStatus — TZ prefill and boolean auto-detect', () => {
  let tmpDir: string;
  let originalAppsDir: string | undefined;

  const compose =
    'services:\n  app:\n    environment:\n' +
    '      TZ: ${TZ:-UTC}\n' +
    '      BEHIND_PROXY: ${NTFY_BEHIND_PROXY:-false}\n' +
    '      PORT: ${NTFY_PORT:-8010}\n';

  beforeEach(() => {
    tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'appenv-tz-'));
    fs.mkdirSync(path.join(tmpDir, 'ntfy'));
    fs.writeFileSync(path.join(tmpDir, 'ntfy', 'compose.yaml'), compose);
    originalAppsDir = process.env.APPS_DIR;
    process.env.APPS_DIR = tmpDir;
  });

  afterEach(() => {
    fs.rmSync(tmpDir, { recursive: true, force: true });
    if (originalAppsDir === undefined) delete process.env.APPS_DIR;
    else process.env.APPS_DIR = originalAppsDir;
  });

  it('prefills an unset TZ with the dashboard-wide timezone', async () => {
    const status = await getServiceEnvStatus('ntfy');
    const tz = status?.fields.find((f) => f.key === 'TZ');
    expect(tz?.isSet).toBe(false);
    expect(tz?.suggestedValue).toBe('Europe/Lisbon');
  });

  it('does not prefill TZ once the app pins its own', async () => {
    fs.writeFileSync(path.join(tmpDir, 'ntfy', '.env'), 'TZ=America/New_York\n');
    const status = await getServiceEnvStatus('ntfy');
    const tz = status?.fields.find((f) => f.key === 'TZ');
    expect(tz?.suggestedValue).toBeNull();
  });

  it('auto-detects a field defaulting to true/false as boolean', async () => {
    const status = await getServiceEnvStatus('ntfy');
    expect(status?.fields.find((f) => f.key === 'NTFY_BEHIND_PROXY')?.boolean).toBe(true);
    expect(status?.fields.find((f) => f.key === 'NTFY_PORT')?.boolean).toBe(false);
  });
});

// Vaultwarden's registry entry declares managedEnvKeys (DOMAIN),
// booleanEnvKeys (SIGNUPS_ALLOWED) and hiddenGeneratedSecrets (ADMIN_TOKEN).
describe('appEnv — Vaultwarden managed / boolean / hidden keys', () => {
  let tmpDir: string;
  let originalAppsDir: string | undefined;

  const compose =
    'services:\n  vaultwarden:\n    environment:\n' +
    '      DOMAIN: ${VAULTWARDEN_DOMAIN:-http://localhost:8222}\n' +
    '      SIGNUPS_ALLOWED: ${VAULTWARDEN_SIGNUPS_ALLOWED:-true}\n' +
    '      ADMIN_TOKEN: ${VAULTWARDEN_ADMIN_TOKEN}\n';

  beforeEach(() => {
    tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'appenv-vw-'));
    fs.mkdirSync(path.join(tmpDir, 'vaultwarden'));
    fs.writeFileSync(path.join(tmpDir, 'vaultwarden', 'docker-compose.yml'), compose);
    originalAppsDir = process.env.APPS_DIR;
    process.env.APPS_DIR = tmpDir;
  });

  afterEach(() => {
    fs.rmSync(tmpDir, { recursive: true, force: true });
    if (originalAppsDir === undefined) {
      delete process.env.APPS_DIR;
    } else {
      process.env.APPS_DIR = originalAppsDir;
    }
  });

  it('flags DOMAIN as managed and read-only, not required', async () => {
    const status = await getServiceEnvStatus('vaultwarden');
    const domain = status?.fields.find((f) => f.key === 'VAULTWARDEN_DOMAIN');
    expect(domain?.managed).toBe(true);
    expect(domain?.required).toBe(false);
  });

  it('flags SIGNUPS_ALLOWED as a boolean field', async () => {
    const status = await getServiceEnvStatus('vaultwarden');
    const signups = status?.fields.find((f) => f.key === 'VAULTWARDEN_SIGNUPS_ALLOWED');
    expect(signups?.boolean).toBe(true);
    expect(signups?.secret).toBe(false);
  });

  it('flags ADMIN_TOKEN as hidden + secret and never suggests a visible value', async () => {
    const status = await getServiceEnvStatus('vaultwarden');
    const token = status?.fields.find((f) => f.key === 'VAULTWARDEN_ADMIN_TOKEN');
    expect(token?.hidden).toBe(true);
    expect(token?.secret).toBe(true);
    expect(token?.required).toBe(false);
    expect(token?.suggestedValue).toBeNull();
  });

  it('generates ADMIN_TOKEN on first save and ignores a client-sent DOMAIN', async () => {
    const { changedKeys } = await saveServiceEnv('vaultwarden', {
      VAULTWARDEN_SIGNUPS_ALLOWED: 'false',
      VAULTWARDEN_DOMAIN: 'https://evil.example.com',
    });

    const written = fs.readFileSync(path.join(tmpDir, 'vaultwarden', '.env'), 'utf8');
    expect(written).toMatch(/^VAULTWARDEN_ADMIN_TOKEN=[0-9a-f]{64}$/m);
    expect(written).toMatch(/^VAULTWARDEN_SIGNUPS_ALLOWED=false$/m);
    expect(written).not.toContain('evil.example.com');
    expect(changedKeys).toContain('VAULTWARDEN_ADMIN_TOKEN');
    expect(changedKeys).not.toContain('VAULTWARDEN_DOMAIN');
  });

  it('does not regenerate ADMIN_TOKEN once it is already set', async () => {
    fs.writeFileSync(
      path.join(tmpDir, 'vaultwarden', '.env'),
      'VAULTWARDEN_ADMIN_TOKEN=keep-this-token\n'
    );
    await saveServiceEnv('vaultwarden', { VAULTWARDEN_SIGNUPS_ALLOWED: 'false' });
    const written = fs.readFileSync(path.join(tmpDir, 'vaultwarden', '.env'), 'utf8');
    expect(written).toContain('VAULTWARDEN_ADMIN_TOKEN=keep-this-token');
  });
});

// n8n declares hiddenGeneratedSecrets ['N8N_DB_PASSWORD'] +
// autoGeneratedSecrets ['N8N_ENCRYPTION_KEY'] in the registry.
describe('ensureGeneratedSecrets', () => {
  let tmpDir: string;
  let originalAppsDir: string | undefined;

  const compose =
    'services:\n  n8n:\n    environment:\n' +
    '      DB_PASS: ${N8N_DB_PASSWORD}\n' +
    '      ENC: ${N8N_ENCRYPTION_KEY}\n' +
    '      HOST: ${N8N_HOST:-localhost}\n';

  beforeEach(() => {
    tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'appenv-gen-'));
    fs.mkdirSync(path.join(tmpDir, 'n8n'));
    fs.writeFileSync(path.join(tmpDir, 'n8n', 'docker-compose.yml'), compose);
    originalAppsDir = process.env.APPS_DIR;
    process.env.APPS_DIR = tmpDir;
  });

  afterEach(() => {
    fs.rmSync(tmpDir, { recursive: true, force: true });
    if (originalAppsDir === undefined) {
      delete process.env.APPS_DIR;
    } else {
      process.env.APPS_DIR = originalAppsDir;
    }
  });

  it('creates .env from .env.example and fills blank + placeholder secrets', async () => {
    fs.writeFileSync(
      path.join(tmpDir, 'n8n', '.env.example'),
      'N8N_DB_PASSWORD=\nN8N_ENCRYPTION_KEY=change-me\nN8N_HOST=localhost\n'
    );

    const changed = await ensureGeneratedSecrets('n8n');

    expect(changed.sort()).toEqual(['N8N_DB_PASSWORD', 'N8N_ENCRYPTION_KEY']);
    const written = fs.readFileSync(path.join(tmpDir, 'n8n', '.env'), 'utf8');
    expect(written).toMatch(/^N8N_DB_PASSWORD=[0-9a-f]{64}$/m);
    expect(written).toMatch(/^N8N_ENCRYPTION_KEY=[0-9a-f]{64}$/m);
    expect(written).toContain('N8N_HOST=localhost');
  });

  it('leaves an already-set secret untouched (never rotates)', async () => {
    fs.writeFileSync(
      path.join(tmpDir, 'n8n', '.env'),
      'N8N_DB_PASSWORD=real-db-pass\nN8N_ENCRYPTION_KEY=real-enc-key\n'
    );

    const changed = await ensureGeneratedSecrets('n8n');

    expect(changed).toEqual([]);
    const written = fs.readFileSync(path.join(tmpDir, 'n8n', '.env'), 'utf8');
    expect(written).toContain('N8N_DB_PASSWORD=real-db-pass');
    expect(written).toContain('N8N_ENCRYPTION_KEY=real-enc-key');
  });

  it('is a no-op for a service with no generatable secrets declared', async () => {
    fs.mkdirSync(path.join(tmpDir, 'dozzle'));
    fs.writeFileSync(path.join(tmpDir, 'dozzle', 'docker-compose.yml'), 'services:\n  dozzle:\n    image: x\n');
    const changed = await ensureGeneratedSecrets('dozzle');
    expect(changed).toEqual([]);
    expect(fs.existsSync(path.join(tmpDir, 'dozzle', '.env'))).toBe(false);
  });
});
