/**
 * Per-app .env configuration, driven from the dashboard instead of manual
 * file editing. Reads/writes apps/<name>/.env directly — the backend's
 * APPS_DIR mount is read-write for exactly this purpose.
 */

import crypto from 'crypto';
import fs from 'fs';
import path from 'path';
import { extractComposeEnvVars, getService, resolveComposeFile } from '../config/services';
import { parseEnvFile } from '../utils/envFile';
import { getPortsInUseByOtherServices, isPortKey, nextFreePort } from './ports';
import { buildExposureEnvOverrides } from './exposureEnv';
import { getAppTimezone } from '../utils/generalSettings';
import logger from '../utils/logger';
import { HttpError } from '../types';

// A generatable secret still holding one of these is treated as "not set" —
// so a stack cloned with the .env.example placeholders still gets real values
// generated on first start rather than booting with a known password.
const SECRET_PLACEHOLDERS = new Set(['', 'change-me', 'changeme', 'change_me', 'changethis', 'secret', 'password']);

// Values for keys matching this are never echoed back to the client, only
// whether they're currently set — same masking pattern as the NPM admin
// password in the global exposure settings.
const SECRET_KEY_PATTERN = /PASSWORD|SECRET|TOKEN|_KEY$|APIKEY/i;

export interface ServiceEnvField {
  key: string;
  required: boolean;
  secret: boolean;
  isSet: boolean;
  // A plain boolean toggle — the dashboard renders true/false radios instead
  // of a text field. Set for `booleanEnvKeys` and auto-detected for any field
  // whose current value or compose default is exactly "true"/"false".
  boolean: boolean;
  // Filled and persisted automatically on save, never shown to the user
  // (`hiddenGeneratedSecrets`). The dashboard renders nothing for it.
  hidden: boolean;
  // Value is derived automatically and shown read-only rather than as an
  // editable field: `managedEnvKeys`, or any key the exposure system
  // overrides at start time (`exposureEnvKeys` url/host/allowedHosts/
  // staticOnExposure) while exposure is enabled. The client never submits it.
  managed: boolean;
  // The effective value for a `managed` field — the exposure-derived value
  // when exposure is on, else null (the UI falls back to value/defaultValue).
  managedValue: string | null;
  // Present only for non-secret fields; secret values are never returned.
  value: string | null;
  defaultValue: string | null;
  // A value to pre-fill an unset field with (the client saves it as-is):
  // a freshly generated secret for `autoGeneratedSecrets` keys, or the
  // dashboard-wide timezone for the `TZ` key. Never persisted here.
  suggestedValue: string | null;
  // True for `*_PORT` keys — a host port the dashboard validates against
  // what's already published.
  isPort: boolean;
  // Set only for port fields: whether the field's effective value (current
  // value, or the compose default) is a host port another service already
  // publishes, and if so the next free port to offer instead.
  portInUse: boolean;
  suggestedPort: number | null;
}

export interface ServiceEnvStatus {
  envFileExists: boolean;
  fields: ServiceEnvField[];
}

async function loadStatus(
  serviceName: string,
  appDir: string,
  composeFile: string,
  projectName: string | null
): Promise<ServiceEnvStatus> {
  const composeContent = fs.readFileSync(composeFile, 'utf8');
  const envVars = extractComposeEnvVars(composeContent);
  const envFilePath = path.join(appDir, '.env');
  const envFileExists = fs.existsSync(envFilePath);
  const currentValues = envFileExists ? parseEnvFile(envFilePath) : {};
  const service = getService(serviceName);
  const hiddenGeneratedSecrets = service?.hiddenGeneratedSecrets ?? [];
  const autoGeneratedSecrets = [...(service?.autoGeneratedSecrets ?? []), ...hiddenGeneratedSecrets];
  const booleanKeys = new Set(service?.booleanEnvKeys ?? []);
  const managedKeys = new Set(service?.managedEnvKeys ?? []);

  // Values the exposure system injects at `docker compose up` (empty unless
  // exposure is enabled + a base domain is configured). Any key here is shown
  // read-only in the panel, at its exposure-derived value.
  const exposureOverrides = await buildExposureEnvOverrides(serviceName, appDir);
  const globalTimezone = await getAppTimezone();

  const hasPortField = envVars.some((envVar) => isPortKey(envVar.key));
  const portsInUse = hasPortField ? await getPortsInUseByOtherServices(projectName) : new Set<number>();

  const fields: ServiceEnvField[] = envVars.map((envVar) => {
    const hidden = hiddenGeneratedSecrets.includes(envVar.key);
    const managedByExposure = Object.prototype.hasOwnProperty.call(exposureOverrides, envVar.key);
    const managed = managedKeys.has(envVar.key) || managedByExposure;
    const secret = hidden || SECRET_KEY_PATTERN.test(envVar.key);
    const currentValue = currentValues[envVar.key];
    const isSet = Boolean(currentValue);

    const effectiveForType = (currentValue ?? envVar.defaultValue ?? '').trim().toLowerCase();
    const boolean = booleanKeys.has(envVar.key) || effectiveForType === 'true' || effectiveForType === 'false';

    const isPort = isPortKey(envVar.key);
    const effectivePort = isPort ? Number.parseInt(currentValue ?? envVar.defaultValue ?? '', 10) : NaN;
    const portInUse = Number.isFinite(effectivePort) && portsInUse.has(effectivePort);

    const suggestedValue =
      !isSet && !hidden && envVar.key === 'TZ'
        ? globalTimezone
        : !isSet && !hidden && autoGeneratedSecrets.includes(envVar.key)
          ? crypto.randomBytes(32).toString('hex')
          : null;

    return {
      key: envVar.key,
      // Hidden secrets are generated on save; managed keys come from exposure —
      // neither is something the user must fill in.
      required: envVar.required && !hidden && !managed,
      secret,
      isSet,
      boolean,
      hidden,
      managed,
      managedValue: managedByExposure ? exposureOverrides[envVar.key] : null,
      value: secret ? null : currentValue ?? null,
      defaultValue: envVar.defaultValue,
      suggestedValue,
      isPort,
      portInUse,
      suggestedPort: portInUse ? nextFreePort(effectivePort + 1, portsInUse) : null,
    };
  });

  return { envFileExists, fields };
}

export async function getServiceEnvStatus(serviceName: string): Promise<ServiceEnvStatus | null> {
  const resolved = resolveComposeFile(serviceName);
  if (!resolved?.composeFile) {
    return null;
  }
  return loadStatus(serviceName, resolved.appDir, resolved.composeFile, resolved.projectName);
}

/**
 * Merge `values` into the app's .env (creating it from .env.example if
 * missing), preserving every other existing line untouched. Empty/blank
 * values are skipped so a masked secret field can be left as-is by the
 * client without clearing it.
 */
export async function saveServiceEnv(
  serviceName: string,
  values: Record<string, string>
): Promise<{ status: ServiceEnvStatus; changedKeys: string[] }> {
  const resolved = resolveComposeFile(serviceName);
  if (!resolved?.composeFile) {
    throw { statusCode: 404, message: `Service ${serviceName} is not installed.` } as HttpError;
  }

  await assertPortsAvailable(serviceName, resolved.projectName, values);

  const envFilePath = path.join(resolved.appDir, '.env');
  const exampleFilePath = path.join(resolved.appDir, '.env.example');

  let baseContent = '';
  if (fs.existsSync(envFilePath)) {
    baseContent = fs.readFileSync(envFilePath, 'utf8');
  } else if (fs.existsSync(exampleFilePath)) {
    baseContent = fs.readFileSync(exampleFilePath, 'utf8');
  }

  const service = getService(serviceName);
  const managedKeys = new Set(service?.managedEnvKeys ?? []);

  const pendingUpdates = new Map(
    Object.entries(values)
      // Exposure-managed keys (e.g. Vaultwarden's DOMAIN) are driven from the
      // hostname at start time — never written here, even if the client sends one.
      .filter(([key]) => !managedKeys.has(key))
      .map(([key, value]) => [key, value.trim()] as const)
      .filter(([, value]) => value !== '')
  );

  // Fill any hidden generated secret the user never sees (e.g. Vaultwarden's
  // ADMIN_TOKEN) with a fresh random value the first time config is saved.
  const currentValues = fs.existsSync(envFilePath) ? parseEnvFile(envFilePath) : {};
  for (const key of service?.hiddenGeneratedSecrets ?? []) {
    if (!currentValues[key] && !pendingUpdates.has(key)) {
      pendingUpdates.set(key, crypto.randomBytes(32).toString('hex'));
    }
  }

  const changedKeys: string[] = [];
  const lines = baseContent.length ? baseContent.split(/\r?\n/) : [];
  const updatedLines = lines.map((line) => {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) {
      return line;
    }
    const eqIndex = trimmed.indexOf('=');
    if (eqIndex <= 0) {
      return line;
    }
    const key = trimmed.slice(0, eqIndex).trim();
    if (pendingUpdates.has(key)) {
      changedKeys.push(key);
      const value = pendingUpdates.get(key)!;
      pendingUpdates.delete(key);
      return `${key}=${value}`;
    }
    return line;
  });

  for (const [key, value] of pendingUpdates) {
    changedKeys.push(key);
    updatedLines.push(`${key}=${value}`);
  }

  const finalContent = updatedLines.join('\n').replace(/\n*$/, '\n');
  fs.writeFileSync(envFilePath, finalContent, { mode: 0o640 });

  return {
    status: await loadStatus(serviceName, resolved.appDir, resolved.composeFile, resolved.projectName),
    changedKeys,
  };
}

/**
 * Fill any of a service's declared generatable secrets (`autoGeneratedSecrets`
 * + `hiddenGeneratedSecrets`) that are still unset — or left at a well-known
 * placeholder like `change-me` — with a fresh random value, right before the
 * service starts. So an app whose only outstanding config is generatable
 * secrets comes up with no dashboard step at all (project principle §0.3).
 *
 * Only touches blank/placeholder values: a secret already holding a real value
 * is never rotated, so this can't break a Postgres/app that has already
 * initialised with the current one. No-op for services without generatable
 * secrets declared.
 */
export async function ensureGeneratedSecrets(serviceName: string): Promise<string[]> {
  const service = getService(serviceName);
  const keys = [...(service?.autoGeneratedSecrets ?? []), ...(service?.hiddenGeneratedSecrets ?? [])];
  if (!keys.length) {
    return [];
  }

  const resolved = resolveComposeFile(serviceName);
  if (!resolved?.composeFile) {
    return [];
  }

  const envFilePath = path.join(resolved.appDir, '.env');
  const exampleFilePath = path.join(resolved.appDir, '.env.example');
  const base = fs.existsSync(envFilePath) ? envFilePath : fs.existsSync(exampleFilePath) ? exampleFilePath : null;
  const currentValues = base ? parseEnvFile(base) : {};

  const generated: Record<string, string> = {};
  for (const key of keys) {
    if (SECRET_PLACEHOLDERS.has((currentValues[key] ?? '').trim().toLowerCase())) {
      // Laravel's APP_KEY must be exactly 32 bytes, conventionally as
      // `base64:<b64 of 32 bytes>` — a 64-char hex string is 64 bytes and
      // makes the app 500 on boot ("incorrect key length").
      generated[key] = /(^|_)APP_KEY$/.test(key)
        ? `base64:${crypto.randomBytes(32).toString('base64')}`
        : crypto.randomBytes(32).toString('hex');
    }
  }

  if (!Object.keys(generated).length) {
    return [];
  }

  const { changedKeys } = await saveServiceEnv(serviceName, generated);
  if (changedKeys.length) {
    logger.info(`Generated ${changedKeys.length} secret(s) for ${serviceName}`, { service: serviceName, keys: changedKeys });
  }
  return changedKeys;
}

/**
 * Reject a save that would point a `*_PORT` field at a host port another
 * service already publishes — `docker compose up` would fail with "port is
 * already allocated" and leave the app stuck in `created`. Ports this
 * service's own project already publishes are fine (it's re-saving its own).
 */
async function assertPortsAvailable(
  serviceName: string,
  projectName: string | null,
  values: Record<string, string>
): Promise<void> {
  const portEntries = Object.entries(values).filter(([key]) => isPortKey(key));
  if (!portEntries.length) {
    return;
  }

  const portsInUse = await getPortsInUseByOtherServices(projectName);
  for (const [key, raw] of portEntries) {
    const port = Number.parseInt(String(raw).trim(), 10);
    if (Number.isFinite(port) && portsInUse.has(port)) {
      throw {
        statusCode: 409,
        message: `Port ${port} is already in use by another service — pick a different ${key}.`,
      } as HttpError;
    }
  }
}
