import fs from 'fs';
import os from 'os';
import path from 'path';
import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import { getServiceEnvStatus, saveServiceEnv } from './appEnv';

// 'vikunja' is a real registry entry with autoGeneratedSecrets:
// ['VIKUNJA_JWT_SECRET']. Point APPS_DIR at a temp root and write a compose
// file under <tmp>/vikunja/ so resolveComposeFile() finds it without
// depending on the checked-in fixtures under apps/.
describe('getServiceEnvStatus — auto-generated secrets', () => {
  let tmpDir: string;
  let originalAppsDir: string | undefined;

  const compose = 'services:\n  app:\n    environment:\n      JWT: ${VIKUNJA_JWT_SECRET}\n      URL: ${VIKUNJA_PUBLIC_URL:-http://localhost:3456}\n';

  beforeEach(() => {
    tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'appenv-test-'));
    fs.mkdirSync(path.join(tmpDir, 'vikunja'));
    fs.writeFileSync(path.join(tmpDir, 'vikunja', 'compose.yaml'), compose);
    originalAppsDir = process.env.APPS_DIR;
    process.env.APPS_DIR = tmpDir;
  });

  afterEach(() => {
    fs.rmSync(tmpDir, { recursive: true, force: true });
    if (originalAppsDir === undefined) {
      delete process.env.APPS_DIR;
    } else {
      process.env.APPS_DIR = originalAppsDir;
    }
  });

  it('suggests a generated value for an unset auto-generated secret', async () => {
    const status = await getServiceEnvStatus('vikunja');
    const jwt = status?.fields.find((f) => f.key === 'VIKUNJA_JWT_SECRET');
    expect(jwt?.secret).toBe(true);
    expect(jwt?.isSet).toBe(false);
    expect(jwt?.suggestedValue).toMatch(/^[0-9a-f]{64}$/);
  });

  it('does not suggest a value once the secret is already set', async () => {
    fs.writeFileSync(path.join(tmpDir, 'vikunja', '.env'), 'VIKUNJA_JWT_SECRET=already-here\n');
    const status = await getServiceEnvStatus('vikunja');
    const jwt = status?.fields.find((f) => f.key === 'VIKUNJA_JWT_SECRET');
    expect(jwt?.isSet).toBe(true);
    expect(jwt?.suggestedValue).toBeNull();
  });

  it('never suggests a value for fields not in autoGeneratedSecrets', async () => {
    const status = await getServiceEnvStatus('vikunja');
    const url = status?.fields.find((f) => f.key === 'VIKUNJA_PUBLIC_URL');
    expect(url?.suggestedValue).toBeNull();
  });
});

// Vaultwarden's registry entry declares managedEnvKeys (DOMAIN),
// booleanEnvKeys (SIGNUPS_ALLOWED) and hiddenGeneratedSecrets (ADMIN_TOKEN).
describe('appEnv — Vaultwarden managed / boolean / hidden keys', () => {
  let tmpDir: string;
  let originalAppsDir: string | undefined;

  const compose =
    'services:\n  vaultwarden:\n    environment:\n' +
    '      DOMAIN: ${VAULTWARDEN_DOMAIN:-http://localhost:8222}\n' +
    '      SIGNUPS_ALLOWED: ${VAULTWARDEN_SIGNUPS_ALLOWED:-true}\n' +
    '      ADMIN_TOKEN: ${VAULTWARDEN_ADMIN_TOKEN}\n';

  beforeEach(() => {
    tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'appenv-vw-'));
    fs.mkdirSync(path.join(tmpDir, 'vaultwarden'));
    fs.writeFileSync(path.join(tmpDir, 'vaultwarden', 'docker-compose.yml'), compose);
    originalAppsDir = process.env.APPS_DIR;
    process.env.APPS_DIR = tmpDir;
  });

  afterEach(() => {
    fs.rmSync(tmpDir, { recursive: true, force: true });
    if (originalAppsDir === undefined) {
      delete process.env.APPS_DIR;
    } else {
      process.env.APPS_DIR = originalAppsDir;
    }
  });

  it('flags DOMAIN as managed and read-only, not required', async () => {
    const status = await getServiceEnvStatus('vaultwarden');
    const domain = status?.fields.find((f) => f.key === 'VAULTWARDEN_DOMAIN');
    expect(domain?.managed).toBe(true);
    expect(domain?.required).toBe(false);
  });

  it('flags SIGNUPS_ALLOWED as a boolean field', async () => {
    const status = await getServiceEnvStatus('vaultwarden');
    const signups = status?.fields.find((f) => f.key === 'VAULTWARDEN_SIGNUPS_ALLOWED');
    expect(signups?.boolean).toBe(true);
    expect(signups?.secret).toBe(false);
  });

  it('flags ADMIN_TOKEN as hidden + secret and never suggests a visible value', async () => {
    const status = await getServiceEnvStatus('vaultwarden');
    const token = status?.fields.find((f) => f.key === 'VAULTWARDEN_ADMIN_TOKEN');
    expect(token?.hidden).toBe(true);
    expect(token?.secret).toBe(true);
    expect(token?.required).toBe(false);
    expect(token?.suggestedValue).toBeNull();
  });

  it('generates ADMIN_TOKEN on first save and ignores a client-sent DOMAIN', async () => {
    const { changedKeys } = await saveServiceEnv('vaultwarden', {
      VAULTWARDEN_SIGNUPS_ALLOWED: 'false',
      VAULTWARDEN_DOMAIN: 'https://evil.example.com',
    });

    const written = fs.readFileSync(path.join(tmpDir, 'vaultwarden', '.env'), 'utf8');
    expect(written).toMatch(/^VAULTWARDEN_ADMIN_TOKEN=[0-9a-f]{64}$/m);
    expect(written).toMatch(/^VAULTWARDEN_SIGNUPS_ALLOWED=false$/m);
    expect(written).not.toContain('evil.example.com');
    expect(changedKeys).toContain('VAULTWARDEN_ADMIN_TOKEN');
    expect(changedKeys).not.toContain('VAULTWARDEN_DOMAIN');
  });

  it('does not regenerate ADMIN_TOKEN once it is already set', async () => {
    fs.writeFileSync(
      path.join(tmpDir, 'vaultwarden', '.env'),
      'VAULTWARDEN_ADMIN_TOKEN=keep-this-token\n'
    );
    await saveServiceEnv('vaultwarden', { VAULTWARDEN_SIGNUPS_ALLOWED: 'false' });
    const written = fs.readFileSync(path.join(tmpDir, 'vaultwarden', '.env'), 'utf8');
    expect(written).toContain('VAULTWARDEN_ADMIN_TOKEN=keep-this-token');
  });
});
