/**
 * Generates the *managed* half of Authelia's `identity_providers.oidc.clients`
 * list in `apps/authelia/config/configuration.yml`, from the registry apps
 * that declare an `oidcClient` and are currently exposed (plan.md §270).
 *
 * This is the plumbing the §216/§217 "trust the proxy" work needs for the
 * OIDC group (Immich, Vikunja, Mealie, NocoDB): each of those apps
 * logs in against Authelia's own OIDC provider instead of showing a second
 * login form. NetBird's client (also in that list) stays hand-maintained —
 * it is a public/PKCE client with bespoke audience/device-code wiring — so
 * the managed block is spliced in *above* the static entries, marker-
 * delimited exactly like `access_control` (see autheliaAccessControl.ts).
 *
 * Secrets: each app's `client_secret` is a random value generated with no
 * user step (`autoGeneratedSecrets` on the service, filled by appEnv.ts) and
 * read back here from the app's `.env`. The app's own OIDC config keeps that
 * plaintext; into `configuration.yml` we write a `$pbkdf2-sha512$` digest
 * (`pbkdf2ClientSecretDigest` below) — Authelia deprecated plaintext client
 * secrets ("will be removed in the near future") and pushes pbkdf2/sha2crypt
 * over bcrypt/argon2 because the secret is verified on *every* token request.
 *
 * Like `access_control`, a change here needs an Authelia restart (502s every
 * gated app briefly), so this only restarts when the rendered block actually
 * moved, and only runs on an exposure change.
 */

import { execFile } from 'child_process';
import { promisify } from 'util';
import crypto from 'crypto';
import fs from 'fs';
import path from 'path';
import { writeAuditLog } from '../utils/audit';
import logger from '../utils/logger';
import { getAllServices, resolveComposeFile } from '../config/services';
import { parseEnvFile } from '../utils/envFile';
import { getAppAccessOptions } from './userAppAccess';
import { getUsersDatabasePath } from './autheliaUsers';

const execFileAsync = promisify(execFile);

const MARK_BEGIN =
  '      # >>> managed by the dashboard — plan.md §270; OIDC clients for exposed apps with `oidcClient` in the registry. Manual edits are lost.';
const MARK_END = '      # <<< managed by the dashboard';

/** `configuration.yml` sits next to `users_database.yml` in the authelia app. */
function getConfigPath(): string | null {
  const usersPath = getUsersDatabasePath();
  return usersPath ? path.join(path.dirname(usersPath), 'configuration.yml') : null;
}

export interface ManagedOidcClient {
  id: string;
  name: string;
  secret: string;
  redirectUris: string[];
  scopes: string[];
  // Per-app overrides (§274). Default: no PKCE requirement, client_secret_post.
  requirePkce?: boolean;
  tokenEndpointAuthMethod?: 'client_secret_post' | 'client_secret_basic';
}

const PBKDF2_ITERATIONS = 310_000; // Authelia's own default for `crypto hash generate pbkdf2`.

/** passlib "ab64": standard base64 with `+`→`.` and no `=` padding — what go-crypt emits. */
function ab64(buf: Buffer): string {
  return buf.toString('base64').replace(/\+/g, '.').replace(/=+$/, '');
}

/**
 * A `$pbkdf2-sha512$<iterations>$<salt>$<key>` digest of `secret`, byte-for-byte
 * in the format `authelia crypto hash generate pbkdf2` produces (verified live,
 * plan.md §281) — so Authelia accepts it as a hashed `client_secret`.
 *
 * The salt is derived from the secret (sha256, first 16 bytes) rather than
 * random, so the same secret always renders the same digest: a random salt
 * would rewrite `configuration.yml` and restart Authelia on every exposure
 * reconcile (see the "only restart when the block moved" note above).
 *   ponytail: deterministic salt. Safe here — every app's secret is a distinct
 *   32+ char auto-generated value, so "same secret ⇒ same digest" never
 *   happens across clients. If secrets ever stop being unique-random, switch
 *   to a random salt cached in the app's .env.
 */
export function pbkdf2ClientSecretDigest(secret: string): string {
  const salt = crypto.createHash('sha256').update(secret).digest().subarray(0, 16);
  const key = crypto.pbkdf2Sync(secret, salt, PBKDF2_ITERATIONS, 64, 'sha512');
  return `$pbkdf2-sha512$${PBKDF2_ITERATIONS}$${ab64(salt)}$${ab64(key)}`;
}

/** Render the marker-delimited managed client entries (6-space list indent). */
export function renderOidcClientsBlock(clients: ManagedOidcClient[]): string {
  const lines: string[] = [MARK_BEGIN];
  for (const client of clients) {
    lines.push(
      `      - client_id: '${client.id}'`,
      `        client_name: '${client.name}'`,
      `        client_secret: '${pbkdf2ClientSecretDigest(client.secret)}'`,
      `        authorization_policy: 'one_factor'`,
      // Skip the OAuth consent screen. Every managed client is a first-party
      // app the operator runs, already gated by Authelia's own login — a
      // "do you allow Vikunja to see your profile?" prompt on your own
      // deployment is pure friction (proven live, §280).
      `        consent_mode: 'implicit'`,
      ...(client.requirePkce
        ? [`        require_pkce: true`, `        pkce_challenge_method: 'S256'`]
        : []),
      `        redirect_uris:`,
      ...client.redirectUris.map((uri) => `          - '${uri}'`),
      `        scopes:`,
      ...client.scopes.map((scope) => `          - '${scope}'`),
      `        token_endpoint_auth_method: '${client.tokenEndpointAuthMethod ?? 'client_secret_post'}'`
    );
  }
  lines.push(MARK_END, '');
  return lines.join('\n');
}

const MARKED = new RegExp(
  `${MARK_BEGIN.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}[\\s\\S]*?${MARK_END.replace(
    /[.*+?^${}()|[\]\\]/g,
    '\\$&'
  )}\\n`
);

/**
 * Put the managed block directly under the `clients:` key, above the static
 * (hand-maintained) client entries. Anchors on the managed marker pair if
 * present, else inserts after `clients:`. Returns the text unchanged if the
 * file has no `oidc.clients` list at all (no OIDC provider configured).
 */
export function spliceOidcClients(configText: string, block: string): string {
  if (MARKED.test(configText)) {
    return configText.replace(MARKED, block);
  }
  const clientsKey = /^ {4}clients:\n/m;
  if (clientsKey.test(configText)) {
    return configText.replace(clientsKey, (m) => m + block);
  }
  return configText;
}

/** The exposed apps that declare an `oidcClient`, as ManagedOidcClient rows. */
function getManagedClients(hostnameByService: Map<string, string>): ManagedOidcClient[] {
  const clients: ManagedOidcClient[] = [];
  for (const service of getAllServices()) {
    const spec = service.oidcClient;
    const hostname = hostnameByService.get(service.name);
    if (!spec || !hostname) {
      continue;
    }
    const resolved = resolveComposeFile(service.name);
    const envPath = resolved ? path.join(resolved.appDir, '.env') : null;
    const envValues = envPath && fs.existsSync(envPath) ? parseEnvFile(envPath) : {};
    const secret = envValues[spec.secretEnvKey];
    if (!secret) {
      logger.warn(
        `Authelia OIDC client for ${service.name}: ${spec.secretEnvKey} is unset in its .env — skipping (save the app's config once to generate it)`
      );
      continue;
    }
    clients.push({
      id: service.name,
      name: service.label,
      secret,
      redirectUris: spec.redirectPaths.map((p) => `https://${hostname}${p}`),
      scopes: spec.scopes ?? ['openid', 'profile', 'email'],
      requirePkce: spec.requirePkce,
      tokenEndpointAuthMethod: spec.tokenEndpointAuthMethod,
    });
  }
  return clients;
}

async function restartAuthelia(): Promise<void> {
  const resolved = resolveComposeFile('authelia');
  if (!resolved?.composeFile) {
    throw new Error('Cannot restart Authelia: its compose file was not found.');
  }
  await execFileAsync(
    'docker',
    ['compose', '-p', resolved.projectName, '-f', resolved.composeFile, 'restart', 'authelia'],
    { timeout: 90_000 }
  );
}

export interface OidcClientsSyncResult {
  changed: boolean;
  restarted: boolean;
  clientCount: number;
  reason?: 'authelia-not-installed';
}

/** Regenerate the managed OIDC client block and, if it moved, restart Authelia. */
export async function syncAutheliaOidcClients(trigger: string): Promise<OidcClientsSyncResult> {
  const configPath = getConfigPath();
  if (!configPath || !fs.existsSync(configPath)) {
    return { changed: false, restarted: false, clientCount: 0, reason: 'authelia-not-installed' };
  }

  const hostnameByService = new Map<string, string>();
  for (const option of await getAppAccessOptions()) {
    if (option.hostname) {
      hostnameByService.set(option.serviceName, option.hostname);
    }
  }
  const clients = getManagedClients(hostnameByService);
  const block = renderOidcClientsBlock(clients);

  const current = fs.readFileSync(configPath, 'utf8');
  const next = spliceOidcClients(current, block);
  if (next === current) {
    return { changed: false, restarted: false, clientCount: clients.length };
  }

  fs.writeFileSync(configPath, next, { mode: 0o640 });
  logger.info(
    `Authelia OIDC clients (${trigger}): wrote ${clients.length} managed client(s); restarting Authelia to apply`
  );
  await restartAuthelia();
  return { changed: true, restarted: true, clientCount: clients.length };
}

/** Never-throws wrapper for the exposure routes: audits a failure, returns a warning string. */
export async function syncAutheliaOidcClientsSafe(
  trigger: string,
  userId: number | null
): Promise<string | null> {
  try {
    const result = await syncAutheliaOidcClients(trigger);
    return result.changed && !result.restarted
      ? 'Authelia OIDC clients were written but the restart did not confirm — check the service.'
      : null;
  } catch (error) {
    const message = (error as Error).message;
    logger.error(`Authelia OIDC clients (${trigger}) failed: ${message}`);
    await writeAuditLog({
      userId,
      action: 'authelia_oidc_clients_sync',
      resource: trigger,
      result: 'failure',
      metadata: { error: message },
    }).catch(() => {});
    return 'The exposure change was saved, but updating Authelia OIDC clients failed — check the server logs.';
  }
}
