import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import fs from 'fs';
import os from 'os';
import path from 'path';
import yaml from 'js-yaml';
import {
  OVERRIDE_FILENAME,
  overridePath,
  readOverride,
  pinnedImages,
  writeImagePins,
  clearImagePins,
  parseImageRef,
  pickLocalDigest,
} from './composeOverride';

let appDir = '';

beforeEach(() => {
  appDir = fs.mkdtempSync(path.join(os.tmpdir(), 'override-'));
});

afterEach(() => {
  fs.rmSync(appDir, { recursive: true, force: true });
});

const pins = (obj: Record<string, string | null>) => new Map(Object.entries(obj));

describe('composeOverride', () => {
  it('writes a parseable override with the managed header and the image pin', () => {
    writeImagePins(appDir, pins({ web: 'nginx:latest@sha256:aaa' }));

    const file = overridePath(appDir);
    expect(file.endsWith(OVERRIDE_FILENAME)).toBe(true);
    const raw = fs.readFileSync(file, 'utf8');
    expect(raw).toContain('# Generated by the Business Lab dashboard');
    expect(yaml.load(raw)).toEqual({ services: { web: { image: 'nginx:latest@sha256:aaa' } } });
    expect([...pinnedImages(appDir).entries()]).toEqual([['web', 'nginx:latest@sha256:aaa']]);
  });

  it('merges new pins into an existing file and leaves untouched services alone', () => {
    writeImagePins(appDir, pins({ web: 'nginx@sha256:a', db: 'postgres:16@sha256:b' }));
    writeImagePins(appDir, pins({ db: 'postgres:16@sha256:c' }));

    expect(readOverride(appDir)).toEqual({
      services: { web: { image: 'nginx@sha256:a' }, db: { image: 'postgres:16@sha256:c' } },
    });
  });

  it('clears a single pin with null, and deletes the file once nothing is left', () => {
    writeImagePins(appDir, pins({ web: 'nginx@sha256:a', db: 'postgres@sha256:b' }));
    writeImagePins(appDir, pins({ web: null }));
    expect([...pinnedImages(appDir).keys()]).toEqual(['db']);

    writeImagePins(appDir, pins({ db: null }));
    expect(fs.existsSync(overridePath(appDir))).toBe(false);
    expect(pinnedImages(appDir).size).toBe(0);
  });

  it('clearImagePins removes the whole file', () => {
    writeImagePins(appDir, pins({ web: 'nginx@sha256:a' }));
    clearImagePins(appDir);
    expect(fs.existsSync(overridePath(appDir))).toBe(false);
  });

  it('treats an unparseable override as no pins rather than throwing', () => {
    fs.writeFileSync(overridePath(appDir), 'services: [this: is: not: valid', 'utf8');
    expect(readOverride(appDir)).toBeNull();
    expect(pinnedImages(appDir).size).toBe(0);
  });

  it('reports no pins when there is no override file', () => {
    expect(readOverride(appDir)).toBeNull();
    expect(pinnedImages(appDir).size).toBe(0);
  });
});

describe('parseImageRef', () => {
  it('sends a bare name to Docker Hub under library/', () => {
    expect(parseImageRef('nginx:alpine')).toEqual({
      registry: 'registry-1.docker.io',
      repository: 'library/nginx',
      reference: 'alpine',
      pinned: false,
    });
  });

  it('defaults the tag to latest', () => {
    expect(parseImageRef('postgres')?.reference).toBe('latest');
  });

  it('keeps a Docker Hub org name as-is', () => {
    expect(parseImageRef('immich/server:v1.2')).toMatchObject({
      registry: 'registry-1.docker.io',
      repository: 'immich/server',
      reference: 'v1.2',
    });
  });

  it('treats a first component with a dot as a registry host', () => {
    expect(parseImageRef('lscr.io/linuxserver/speedtest-tracker:latest')).toMatchObject({
      registry: 'lscr.io',
      repository: 'linuxserver/speedtest-tracker',
    });
  });

  it('treats a registry port as a host, not a tag', () => {
    // The colon is before the last slash, so it cannot be the tag.
    expect(parseImageRef('localhost:5000/team/app')).toMatchObject({
      registry: 'localhost:5000',
      repository: 'team/app',
      reference: 'latest',
    });
  });

  it('marks a digest-pinned ref as pinned, since it cannot go out of date', () => {
    expect(parseImageRef('nginx@sha256:abc')?.pinned).toBe(true);
  });

  it('rejects nonsense rather than guessing', () => {
    expect(parseImageRef('')).toBeNull();
    expect(parseImageRef('two words')).toBeNull();
  });
});

describe('pickLocalDigest', () => {
  it('matches the entry for the repository being checked', () => {
    const digests = ['nginx@sha256:aaa', 'other@sha256:bbb'];
    expect(pickLocalDigest(digests, 'library/nginx')).toBe('sha256:aaa');
  });

  it('matches a registry-qualified entry', () => {
    expect(pickLocalDigest(['lscr.io/linuxserver/grocy@sha256:ccc'], 'linuxserver/grocy')).toBe('sha256:ccc');
  });

  it('falls back to a lone entry whose name does not match', () => {
    expect(pickLocalDigest(['weird@sha256:ddd'], 'something/else')).toBe('sha256:ddd');
  });

  it('returns null for a locally built image, which has no digests at all', () => {
    expect(pickLocalDigest([], 'homelab-backend')).toBeNull();
  });
});
