/**
 * The dashboard-managed `docker-compose.override.yml` for a managed app.
 *
 * Compose files under `apps/<name>/` are read-only to the backend (CLAUDE.md
 * "Never" — the backend generates `.env` and config files, not compose). The
 * update button still needs somewhere to record *which* image an app was moved
 * to, so that a fresh clone (where the app data dir and this file are
 * gitignored) comes back up on the same one rather than whatever `latest` is at
 * day. That record is this file: a minimal override that pins
 * `services.<svc>.image` to `repo:tag@sha256:…` for each image the update
 * pulled.
 *
 * It is passed to every `docker compose` invocation as a second `-f` (see
 * `resolveComposeFile` → `composeArgs`). Explicit `-f` suppresses Compose's
 * automatic override-file discovery, so it has to be listed by hand — which is
 * fine, it also means an unmanaged `docker-compose.override.yml` a user dropped
 * in is picked up too.
 */

import fs from 'fs';
import path from 'path';
import yaml from 'js-yaml';
import logger from '../utils/logger';

export const OVERRIDE_FILENAME = 'docker-compose.override.yml';

const MANAGED_HEADER =
  '# Generated by the Business Lab dashboard (the per-app Update button).\n' +
  '# Pins each image to the exact digest the last update pulled and verified,\n' +
  '# so a fresh clone recreates the same containers. Delete it (or use "Unpin"\n' +
  '# on the app card) to float back to the tags in docker-compose.yml.\n';

interface OverrideDoc {
  services?: Record<string, { image?: string }>;
}

export function overridePath(appDir: string): string {
  return path.join(appDir, OVERRIDE_FILENAME);
}

export function readOverride(appDir: string): OverrideDoc | null {
  const file = overridePath(appDir);
  if (!fs.existsSync(file)) {
    return null;
  }
  try {
    const doc = yaml.load(fs.readFileSync(file, 'utf8'));
    return doc && typeof doc === 'object' ? (doc as OverrideDoc) : null;
  } catch (error) {
    logger.warn('Ignoring an unparseable compose override', { file, error: (error as Error).message });
    return null;
  }
}

/** compose-service -> pinned image ref currently in the override file. */
export function pinnedImages(appDir: string): Map<string, string> {
  const pinned = new Map<string, string>();
  for (const [service, def] of Object.entries(readOverride(appDir)?.services ?? {})) {
    if (def && typeof def.image === 'string' && def.image) {
      pinned.set(service, def.image);
    }
  }
  return pinned;
}

/**
 * Merge image pins into the override file. A `null` value clears that
 * service's pin. When no pins remain the file is removed, so an app with
 * nothing pinned has no override at all rather than an empty `services: {}`.
 */
export function writeImagePins(appDir: string, pins: Map<string, string | null>): void {
  const doc = readOverride(appDir) ?? {};
  const services: Record<string, { image?: string }> = doc.services ?? {};

  for (const [service, ref] of pins) {
    if (ref === null) {
      delete services[service];
    } else {
      services[service] = { ...(services[service] ?? {}), image: ref };
    }
  }

  const file = overridePath(appDir);
  if (Object.keys(services).length === 0) {
    if (fs.existsSync(file)) {
      fs.rmSync(file);
      logger.info('Removed the compose override (nothing left pinned)', { file });
    }
    return;
  }

  doc.services = services;
  fs.writeFileSync(file, MANAGED_HEADER + yaml.dump(doc, { lineWidth: 120 }), 'utf8');
  logger.info('Wrote compose image pins', { file, services: Object.keys(services) });
}

/** Drop the whole override file (the "Unpin" action). */
export function clearImagePins(appDir: string): void {
  const file = overridePath(appDir);
  if (fs.existsSync(file)) {
    fs.rmSync(file);
    logger.info('Cleared all compose image pins', { file });
  }
}
