/**
 * The dashboard-managed `docker-compose.override.yml` for a managed app.
 *
 * Compose files under `apps/<name>/` are read-only to the backend (CLAUDE.md
 * "Never" — the backend generates `.env` and config files, not compose).
 * Managed-app images are only ever pulled as part of a Business Lab
 * self-update (§209 — one deliberate, git-pull-triggered batch across every
 * installed app, not a per-app action), and this file is where that batch
 * records *which* image each app landed on, so that a fresh clone (where the
 * app data dir and this file are gitignored) comes back up on the same one
 * rather than whatever a floating tag resolves to on that day. A minimal
 * override that pins `services.<svc>.image` to `repo:tag@sha256:…` for each
 * image the last self-update pulled.
 *
 * It is passed to every `docker compose` invocation as a second `-f` (see
 * `resolveComposeFile` → `composeArgs`). Explicit `-f` suppresses Compose's
 * automatic override-file discovery, so it has to be listed by hand — which is
 * fine, it also means an unmanaged `docker-compose.override.yml` a user dropped
 * in is picked up too.
 */

import fs from 'fs';
import path from 'path';
import yaml from 'js-yaml';
import logger from '../utils/logger';

export const OVERRIDE_FILENAME = 'docker-compose.override.yml';

const MANAGED_HEADER =
  '# Generated by the Business Lab dashboard (a self-update, §209).\n' +
  '# Pins each image to the exact digest the last self-update pulled and\n' +
  '# verified, so a fresh clone recreates the same containers. Delete it (or\n' +
  '# use "Unpin" on the app card) to float back to the tags in\n' +
  '# docker-compose.yml.\n';

// Docker Hub is the implicit registry for an unqualified image name
// ("nginx", "immich/server") — see parseImageRef below.
const DOCKER_HUB_REGISTRY = 'registry-1.docker.io';

export interface ImageRef {
  registry: string;
  repository: string;
  reference: string;
  // True when the ref pins a digest already — nothing to pin further.
  pinned: boolean;
}

/**
 * Split `lscr.io/linuxserver/speedtest-tracker:latest` into its parts.
 *
 * The first component is a registry host only if it looks like one — a dot, a
 * port, or literally "localhost". `nginx` and `immich/server` are both Docker
 * Hub, and a single-component name lives under `library/`.
 */
export function parseImageRef(image: string): ImageRef | null {
  if (!image || image.includes(' ')) {
    return null;
  }

  const atIndex = image.indexOf('@');
  if (atIndex !== -1) {
    return { registry: '', repository: image.slice(0, atIndex), reference: image.slice(atIndex + 1), pinned: true };
  }

  let remainder = image;
  let registry = DOCKER_HUB_REGISTRY;
  const firstSlash = remainder.indexOf('/');
  if (firstSlash !== -1) {
    const head = remainder.slice(0, firstSlash);
    if (head.includes('.') || head.includes(':') || head === 'localhost') {
      registry = head;
      remainder = remainder.slice(firstSlash + 1);
    }
  }

  // A colon after the last slash is the tag; one before it is a registry port.
  const lastColon = remainder.lastIndexOf(':');
  const lastSlash = remainder.lastIndexOf('/');
  const reference = lastColon > lastSlash ? remainder.slice(lastColon + 1) : 'latest';
  const repository = lastColon > lastSlash ? remainder.slice(0, lastColon) : remainder;

  if (!repository) {
    return null;
  }

  return {
    registry,
    repository: registry === DOCKER_HUB_REGISTRY && !repository.includes('/') ? `library/${repository}` : repository,
    reference,
    pinned: false,
  };
}

/** The digest `docker image inspect --format '{{json .RepoDigests}}'` recorded for this repository, if any. */
export function pickLocalDigest(repoDigests: string[], repository: string): string | null {
  for (const entry of repoDigests) {
    const [repo, digest] = entry.split('@');
    // Docker Hub records these without the library/ prefix it adds on pull.
    if (repo === repository || `library/${repo}` === repository || repo.endsWith(`/${repository}`)) {
      return digest ?? null;
    }
  }
  // A single entry with a name we could not match is still this image's digest.
  return repoDigests.length === 1 ? repoDigests[0].split('@')[1] ?? null : null;
}

interface OverrideDoc {
  services?: Record<string, { image?: string }>;
}

export function overridePath(appDir: string): string {
  return path.join(appDir, OVERRIDE_FILENAME);
}

export function readOverride(appDir: string): OverrideDoc | null {
  const file = overridePath(appDir);
  if (!fs.existsSync(file)) {
    return null;
  }
  try {
    const doc = yaml.load(fs.readFileSync(file, 'utf8'));
    return doc && typeof doc === 'object' ? (doc as OverrideDoc) : null;
  } catch (error) {
    logger.warn('Ignoring an unparseable compose override', { file, error: (error as Error).message });
    return null;
  }
}

/** compose-service -> pinned image ref currently in the override file. */
export function pinnedImages(appDir: string): Map<string, string> {
  const pinned = new Map<string, string>();
  for (const [service, def] of Object.entries(readOverride(appDir)?.services ?? {})) {
    if (def && typeof def.image === 'string' && def.image) {
      pinned.set(service, def.image);
    }
  }
  return pinned;
}

/**
 * Merge image pins into the override file. A `null` value clears that
 * service's pin. When no pins remain the file is removed, so an app with
 * nothing pinned has no override at all rather than an empty `services: {}`.
 */
export function writeImagePins(appDir: string, pins: Map<string, string | null>): void {
  const doc = readOverride(appDir) ?? {};
  const services: Record<string, { image?: string }> = doc.services ?? {};

  for (const [service, ref] of pins) {
    if (ref === null) {
      delete services[service];
    } else {
      services[service] = { ...(services[service] ?? {}), image: ref };
    }
  }

  const file = overridePath(appDir);
  if (Object.keys(services).length === 0) {
    if (fs.existsSync(file)) {
      fs.rmSync(file);
      logger.info('Removed the compose override (nothing left pinned)', { file });
    }
    return;
  }

  doc.services = services;
  fs.writeFileSync(file, MANAGED_HEADER + yaml.dump(doc, { lineWidth: 120 }), 'utf8');
  logger.info('Wrote compose image pins', { file, services: Object.keys(services) });
}

/** Drop the whole override file (the "Unpin" action). */
export function clearImagePins(appDir: string): void {
  const file = overridePath(appDir);
  if (fs.existsSync(file)) {
    fs.rmSync(file);
    logger.info('Cleared all compose image pins', { file });
  }
}
