import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import fs from 'fs';
import os from 'os';
import path from 'path';
import yaml from 'js-yaml';
import {
  OVERRIDE_FILENAME,
  overridePath,
  readOverride,
  pinnedImages,
  writeImagePins,
  clearImagePins,
} from './composeOverride';

let appDir = '';

beforeEach(() => {
  appDir = fs.mkdtempSync(path.join(os.tmpdir(), 'override-'));
});

afterEach(() => {
  fs.rmSync(appDir, { recursive: true, force: true });
});

const pins = (obj: Record<string, string | null>) => new Map(Object.entries(obj));

describe('composeOverride', () => {
  it('writes a parseable override with the managed header and the image pin', () => {
    writeImagePins(appDir, pins({ web: 'nginx:latest@sha256:aaa' }));

    const file = overridePath(appDir);
    expect(file.endsWith(OVERRIDE_FILENAME)).toBe(true);
    const raw = fs.readFileSync(file, 'utf8');
    expect(raw).toContain('# Generated by the Business Lab dashboard');
    expect(yaml.load(raw)).toEqual({ services: { web: { image: 'nginx:latest@sha256:aaa' } } });
    expect([...pinnedImages(appDir).entries()]).toEqual([['web', 'nginx:latest@sha256:aaa']]);
  });

  it('merges new pins into an existing file and leaves untouched services alone', () => {
    writeImagePins(appDir, pins({ web: 'nginx@sha256:a', db: 'postgres:16@sha256:b' }));
    writeImagePins(appDir, pins({ db: 'postgres:16@sha256:c' }));

    expect(readOverride(appDir)).toEqual({
      services: { web: { image: 'nginx@sha256:a' }, db: { image: 'postgres:16@sha256:c' } },
    });
  });

  it('clears a single pin with null, and deletes the file once nothing is left', () => {
    writeImagePins(appDir, pins({ web: 'nginx@sha256:a', db: 'postgres@sha256:b' }));
    writeImagePins(appDir, pins({ web: null }));
    expect([...pinnedImages(appDir).keys()]).toEqual(['db']);

    writeImagePins(appDir, pins({ db: null }));
    expect(fs.existsSync(overridePath(appDir))).toBe(false);
    expect(pinnedImages(appDir).size).toBe(0);
  });

  it('clearImagePins removes the whole file', () => {
    writeImagePins(appDir, pins({ web: 'nginx@sha256:a' }));
    clearImagePins(appDir);
    expect(fs.existsSync(overridePath(appDir))).toBe(false);
  });

  it('treats an unparseable override as no pins rather than throwing', () => {
    fs.writeFileSync(overridePath(appDir), 'services: [this: is: not: valid', 'utf8');
    expect(readOverride(appDir)).toBeNull();
    expect(pinnedImages(appDir).size).toBe(0);
  });

  it('reports no pins when there is no override file', () => {
    expect(readOverride(appDir)).toBeNull();
    expect(pinnedImages(appDir).size).toBe(0);
  });
});
