import { describe, expect, it, vi, beforeEach } from 'vitest';
import yaml from 'js-yaml';
import { buildHomepageServicesYaml, parseHomepageLabels, HomepageTile } from './homepageConfig';

describe('parseHomepageLabels', () => {
  const compose = `services:
  authelia:
    labels:
      - "homepage.group=Security"
      - "homepage.name=Authelia"
      - "homepage.icon=authelia.png"
      - "homepage.href=http://localhost:\${AUTHELIA_PORT:-10100}"
      - "homepage.description=Single sign-on and 2FA gateway"
`;

  it('extracts group/name/icon/description and strips the surrounding quote', () => {
    expect(parseHomepageLabels(compose)).toEqual({
      group: 'Security',
      name: 'Authelia',
      icon: 'authelia.png',
      description: 'Single sign-on and 2FA gateway',
    });
  });

  it('ignores homepage.href — the link comes from exposure, not the label', () => {
    expect(parseHomepageLabels(compose)).not.toHaveProperty('href');
  });

  it('keeps a description that contains an = or a colon', () => {
    const text = '      - "homepage.description=Compare prices: Lidl, Auchan = cheapest"';
    expect(parseHomepageLabels(text).description).toBe('Compare prices: Lidl, Auchan = cheapest');
  });

  it('returns an empty object when there are no homepage labels', () => {
    expect(parseHomepageLabels('services:\n  x:\n    image: y\n')).toEqual({});
  });
});

describe('buildHomepageServicesYaml', () => {
  const tiles: HomepageTile[] = [
    { group: 'Security', name: 'Vaultwarden', href: 'https://vaultwarden.example.com', icon: 'vaultwarden.png' },
    { group: 'Security', name: 'Authelia', href: 'https://authelia.example.com', description: 'SSO', icon: 'authelia.png' },
    { group: 'Media & Files', name: 'Immich', href: 'https://immich.example.com', description: 'Photos' },
  ];

  function parsed(input: HomepageTile[] = tiles) {
    return yaml.load(buildHomepageServicesYaml(input)) as Array<Record<string, Array<Record<string, unknown>>>>;
  }

  it('groups tiles and sorts both groups and tiles alphabetically', () => {
    const doc = parsed();
    expect(doc.map((g) => Object.keys(g)[0])).toEqual(['Media & Files', 'Security']);
    const security = doc[1]['Security'];
    expect(security.map((s) => Object.keys(s)[0])).toEqual(['Authelia', 'Vaultwarden']);
  });

  it('carries href always, and description/icon only when set', () => {
    const doc = parsed();
    expect(doc[1]['Security'][0]).toEqual({
      Authelia: { href: 'https://authelia.example.com', description: 'SSO', icon: 'authelia.png' },
    });
    // Immich has no icon; Vaultwarden has no description.
    expect(doc[0]['Media & Files'][0]).toEqual({
      Immich: { href: 'https://immich.example.com', description: 'Photos' },
    });
    expect(doc[1]['Security'][1]).toEqual({
      Vaultwarden: { href: 'https://vaultwarden.example.com', icon: 'vaultwarden.png' },
    });
  });

  it('carries the "do not edit" header and is valid YAML for an empty list', () => {
    const out = buildHomepageServicesYaml([]);
    expect(out).toContain('Generated by the dashboard');
    expect(yaml.load(out)).toEqual([]);
  });
});

// The running-AND-exposed filter and the href = https://<hostname><webPath>
// construction, with the registry / exposure / docker calls mocked.
vi.mock('../config/services', () => ({
  getAllServices: vi.fn(),
  getService: vi.fn(),
  resolveComposeFile: vi.fn(),
}));
vi.mock('./exposure', () => ({ getServiceExposureRow: vi.fn() }));
vi.mock('../utils/logger', () => ({ default: { info: vi.fn(), warn: vi.fn(), error: vi.fn() } }));
vi.mock('child_process', () => ({ exec: vi.fn() }));
vi.mock('fs/promises', () => ({
  default: {
    readFile: vi.fn(),
    writeFile: vi.fn(),
    mkdir: vi.fn(),
  },
}));

describe('collectHomepageTiles', () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  it('emits a tile only for an app that is both running and provisioned-exposed, with webPath appended', async () => {
    const { getAllServices, getService, resolveComposeFile } = await import('../config/services');
    const { getServiceExposureRow } = await import('./exposure');
    const { exec } = await import('child_process');
    const fs = (await import('fs/promises')).default;

    vi.mocked(getAllServices).mockReturnValue([
      { name: 'waha' },
      { name: 'immich' },
      { name: 'dozzle' },
    ] as never);
    vi.mocked(resolveComposeFile).mockImplementation(
      (name: string) => ({ composeFile: `/repo/apps/${name}/docker-compose.yml`, appDir: `/repo/apps/${name}`, projectName: name }) as never
    );
    vi.mocked(getService).mockImplementation((name: string) => (name === 'waha' ? ({ webPath: '/dashboard' }) : ({})) as never);

    // waha: running + exposed. immich: running, NOT exposed. dozzle: exposed but NOT running.
    vi.mocked(exec).mockImplementation(((_cmd: string, cb: (e: unknown, out: string) => void) => {
      cb(null, 'waha\nimmich\n');
    }) as never);
    vi.mocked(getServiceExposureRow).mockImplementation(
      (name: string) =>
        Promise.resolve(
          name === 'waha'
            ? { enabled: true, status: 'provisioned', hostname: 'waha.example.com' }
            : name === 'dozzle'
              ? { enabled: true, status: 'provisioned', hostname: 'dozzle.example.com' }
              : { enabled: false, status: 'not_provisioned', hostname: null }
        ) as never
    );
    vi.mocked(fs.readFile).mockResolvedValue(
      '    labels:\n      - "homepage.group=Communication"\n      - "homepage.name=WAHA"\n      - "homepage.icon=whatsapp.png"\n      - "homepage.description=WhatsApp HTTP API gateway"\n' as never
    );

    const { collectHomepageTiles } = await import('./homepageConfig');
    const tiles = await collectHomepageTiles();

    expect(tiles).toEqual([
      {
        group: 'Communication',
        name: 'WAHA',
        href: 'https://waha.example.com/dashboard',
        description: 'WhatsApp HTTP API gateway',
        icon: 'whatsapp.png',
      },
    ]);
  });
});
