/**
 * The Home Page (apps/home-page/) is published at the bare domain now (§111),
 * so every tile has to link to the app's public `https://<hostname>` — not the
 * `http://localhost:<port>` baked into each app's `homepage.href` compose
 * label, which is dead for any remote visitor. It also means an app with no
 * public exposure has no useful link and should not show a tile at all
 * (§112.3), and the stock "My First Group" demo content must never render
 * (§112.4).
 *
 * Homepage's label auto-discovery can't express any of that, so the dashboard
 * owns the service list instead: `data/services.yaml` is generated here from
 * the registry, each app's live exposure row, and the `homepage.*` labels
 * (kept as the one source of name/group/icon/description). Regenerated on
 * every start/stop and every exposure toggle — see the callers in
 * executor.ts and routes/services.ts. Homepage hot-reloads the file, so no
 * restart is needed. plan.md §114.
 */

import { exec } from 'child_process';
import fs from 'fs/promises';
import path from 'path';
import yaml from 'js-yaml';
import logger from '../utils/logger';
import { getAllServices, getService, resolveComposeFile } from '../config/services';
import { getServiceExposureRow } from './exposure';

export const HOMEPAGE_SERVICE = 'homepage';

const GENERATED_HEADER = [
  '# Generated by the dashboard from each app\'s exposure state and its',
  '# homepage.* compose labels. Do not edit by hand — starting or stopping any',
  '# app, or toggling its exposure, rewrites this file. See plan.md §114.',
  '',
].join('\n');

export interface HomepageLabels {
  group?: string;
  name?: string;
  icon?: string;
  description?: string;
}

/**
 * Pull the `homepage.*` values out of a compose file. Every app declares them
 * as list-form label strings (`- "homepage.group=Security"`); a raw scan is
 * enough and dodges the map-vs-list ambiguity a YAML walk would hit. `href`
 * is deliberately ignored — the link is derived from exposure, not the label.
 */
export function parseHomepageLabels(composeText: string): HomepageLabels {
  const out: HomepageLabels = {};
  const re = /homepage\.(group|name|icon|description)\s*=\s*(.+?)["']?\s*$/gm;
  let match: RegExpExecArray | null;
  while ((match = re.exec(composeText)) !== null) {
    const key = match[1] as keyof HomepageLabels;
    const value = match[2].replace(/^["']/, '').trim();
    if (value) {
      out[key] = value;
    }
  }
  return out;
}

export interface HomepageTile {
  group: string;
  name: string;
  href: string;
  description?: string;
  icon?: string;
}

/**
 * Render the tiles as Homepage's `services.yaml` shape: a list of
 * `{ Group: [ { Service: { href, … } } ] }`. Groups and services are sorted
 * so the file only changes when the underlying facts do.
 */
export function buildHomepageServicesYaml(tiles: HomepageTile[]): string {
  const byGroup = new Map<string, HomepageTile[]>();
  for (const tile of tiles) {
    const list = byGroup.get(tile.group) ?? [];
    list.push(tile);
    byGroup.set(tile.group, list);
  }

  const doc = [...byGroup.keys()]
    .sort((a, b) => a.localeCompare(b))
    .map((group) => ({
      [group]: byGroup
        .get(group)!
        .sort((a, b) => a.name.localeCompare(b.name))
        .map((tile) => ({
          [tile.name]: {
            href: tile.href,
            ...(tile.description ? { description: tile.description } : {}),
            ...(tile.icon ? { icon: tile.icon } : {}),
          },
        })),
    }));

  // lineWidth: -1 keeps long descriptions on one line rather than folding.
  return GENERATED_HEADER + yaml.dump(doc, { lineWidth: -1 });
}

/** Running compose projects, from a single `docker ps`. Empty on failure. */
function runningProjects(): Promise<Set<string>> {
  return new Promise((resolve) => {
    exec('docker ps --format \'{{.Label "com.docker.compose.project"}}\'', (error, stdout) => {
      if (error) {
        resolve(new Set());
        return;
      }
      resolve(
        new Set(
          stdout
            .trim()
            .split('\n')
            .map((line) => line.trim())
            .filter(Boolean)
        )
      );
    });
  });
}

/**
 * One tile per registry app that is BOTH running AND exposed (an enabled,
 * provisioned `service_exposure` row with a hostname). href is the public
 * URL plus the registry's `webPath` for the app whose UI isn't at the root.
 */
export async function collectHomepageTiles(): Promise<HomepageTile[]> {
  const running = await runningProjects();
  const tiles: HomepageTile[] = [];

  for (const service of getAllServices()) {
    // The Home Page doesn't list itself — a tile linking to the page you are
    // already on is noise.
    if (service.name === HOMEPAGE_SERVICE) {
      continue;
    }
    const resolved = resolveComposeFile(service.name);
    if (!resolved?.composeFile || !resolved.projectName) {
      continue;
    }
    if (!running.has(resolved.projectName)) {
      continue;
    }

    const row = await getServiceExposureRow(service.name).catch(() => null);
    const hostname =
      row && row.enabled && row.status === 'provisioned' && row.hostname ? row.hostname : null;
    if (!hostname) {
      continue;
    }

    let composeText: string;
    try {
      composeText = await fs.readFile(resolved.composeFile, 'utf8');
    } catch {
      continue;
    }

    const labels = parseHomepageLabels(composeText);
    if (!labels.name || !labels.group) {
      continue;
    }

    tiles.push({
      group: labels.group,
      name: labels.name,
      href: `https://${hostname}${getService(service.name)?.webPath ?? ''}`,
      description: labels.description,
      icon: labels.icon,
    });
  }

  return tiles;
}

function homepageDataDir(appDir?: string): string | null {
  if (appDir) {
    return path.join(appDir, 'data');
  }
  const resolved = resolveComposeFile(HOMEPAGE_SERVICE);
  return resolved ? path.join(resolved.appDir, 'data') : null;
}

/**
 * Rewrite `data/services.yaml`. Best-effort: a failure here must never break
 * the start/stop/exposure call that triggered it, so it logs and returns.
 */
export async function regenerateHomepageServices(): Promise<void> {
  try {
    const dataDir = homepageDataDir();
    if (!dataDir) {
      return;
    }
    const tiles = await collectHomepageTiles();
    await fs.mkdir(dataDir, { recursive: true });
    await fs.writeFile(path.join(dataDir, 'services.yaml'), buildHomepageServicesYaml(tiles), 'utf8');
    logger.info('Regenerated Homepage services.yaml', { tiles: tiles.length });
  } catch (error) {
    logger.warn('Could not regenerate Homepage services.yaml', { error: (error as Error).message });
  }
}

/**
 * Runs from composeUpWithManagedConfig when the Home Page itself (re)starts:
 * disable label auto-discovery (the generated services.yaml is the whole
 * list) and clear the stock demo bookmarks — both are noise on a page that is
 * now public. services.yaml itself is written by regenerateHomepageServices,
 * called right after the start.
 */
export async function applyHomepageConfig(serviceName: string, appDir: string): Promise<void> {
  if (serviceName !== HOMEPAGE_SERVICE) {
    return;
  }
  try {
    const dataDir = homepageDataDir(appDir)!;
    await fs.mkdir(dataDir, { recursive: true });
    await fs.writeFile(
      path.join(dataDir, 'docker.yaml'),
      '# Auto-discovery is disabled: the dashboard writes services.yaml from each\n' +
        '# app\'s exposure state and homepage.* labels. See plan.md §114.\n',
      'utf8'
    );
    await fs.writeFile(path.join(dataDir, 'bookmarks.yaml'), `${GENERATED_HEADER}--- []\n`, 'utf8');
  } catch (error) {
    logger.warn('Could not apply Homepage config', { error: (error as Error).message });
  }
}
