/**
 * Copy each newly consumed Paperless document to the Samba share, so a PDF
 * filed in Paperless also shows up over SMB (plan.md §906).
 *
 * Why a post-consume script and not a bind mount over `media/documents/archive`:
 * a mount there hides every existing archive file, and Docker creates a
 * root-owned mountpoint if Paperless has not started yet (§871). The script
 * only sees new documents — existing ones are not back-filled.
 *
 * The script lives in `data/share-copy/`, a sibling of the dirs Paperless's
 * entrypoint chowns (same reasoning as `data/clamav/`, §725), and compose
 * mounts it read-only. Static content, so it is rewritten every start only to
 * keep it matching this file. The base compose file references it
 * unconditionally — unlike the ClamAV hook it does not depend on another app.
 *
 * Best effort by design: the document is already stored when the hook runs, so
 * a failed copy is logged and the exit code stays 0.
 */

import fs from 'fs';
import path from 'path';

const SERVICE = 'paperless';
const SCRIPT_BASENAME = 'post-consume-share.py';

export function postConsumeScriptHostPath(appDir: string): string {
  return path.join(appDir, 'data', 'share-copy', SCRIPT_BASENAME);
}

export function renderPostConsumeScript(): string {
  return `#!/usr/bin/env python3
# Generated by the Business Lab dashboard (services/paperlessShareCopy.ts).
# Copies the document Paperless just consumed to the Samba share. Prefers the
# OCR'd archive PDF; falls back to the original when there is none. Never
# fails the consume: the document is already stored.
import os
import shutil
import sys

DEST = "/usr/src/paperless/share-out"

src = os.environ.get("DOCUMENT_ARCHIVE_PATH") or os.environ.get("DOCUMENT_SOURCE_PATH")
if not src or not os.path.isfile(src):
    print(f"share copy: no file at {src!r}; skipping", file=sys.stderr)
    sys.exit(0)

# The id keeps two scans with the same file name from overwriting each other.
name = os.environ.get("DOCUMENT_FILE_NAME") or os.path.basename(src)
if os.environ.get("DOCUMENT_ARCHIVE_PATH"):
    # The archive is always a PDF, even when the original was a scan image.
    name = os.path.splitext(name)[0] + ".pdf"
try:
    target = os.path.join(DEST, f"{os.environ.get('DOCUMENT_ID', '0')}-{name}")
    shutil.copyfile(src, target)
    os.chmod(target, 0o666)
except OSError as exc:
    print(f"share copy failed: {exc}", file=sys.stderr)
sys.exit(0)
`;
}

export function ensurePaperlessShareCopy(serviceName: string, appDir: string): void {
  if (serviceName !== SERVICE) {
    return;
  }
  const file = postConsumeScriptHostPath(appDir);
  fs.mkdirSync(path.dirname(file), { recursive: true });
  // 0o755: Paperless's uid is not ours, so execute must be on "other".
  fs.writeFileSync(file, renderPostConsumeScript(), { mode: 0o755 });
  fs.chmodSync(file, 0o755);
}
