/**
 * Virus-scan Paperless-ngx document intake against ClamAV — the Paperless half
 * of the §81.7 roster wiring (§179 did the Nextcloud half; see
 * nextcloudClamav.ts).
 *
 * Paperless has no native antivirus. Its only intake hook is
 * `PAPERLESS_PRE_CONSUME_SCRIPT`: a script run against every document before
 * it is consumed, whose non-zero exit aborts consumption
 * (`src/documents/consumer.py` → `run_subprocess(check_exit_code=True)` →
 * `ConsumerError`). Wiring that up needs two things the dashboard has to
 * provide with no console step (§0.2):
 *
 *   1. the scanner script itself, dropped into a path the container can see —
 *      `apps/paperless/data/data/` is bind-mounted at `/usr/src/paperless/data/`
 *      and is writable, so it goes there;
 *   2. the `PAPERLESS_PRE_CONSUME_SCRIPT` env var, which the base compose file
 *      does not reference and cannot be injected via `.env` (no `env_file:`,
 *      no `${...}` for it). That needs a managed compose fragment —
 *      `docker-compose.managed.yml` (config/services.ts MANAGED_COMPOSE_FILENAME),
 *      kept separate from a self-update's image-pin override (§209) so a self-update
 *      cannot wipe it.
 *
 * ClamAV runs as its own compose project, reachable from Paperless's network
 * only via the host gateway + its published port (`CLAMAV_PORT`), the same
 * cross-project trick nextcloudClamav.ts and the exposure code use — so the
 * script speaks clamd's `INSTREAM` over TCP to `<gateway>:<port>`, baked into
 * the script when it is rendered.
 *
 * Fail-open on an unreachable clamd (exit 0), matching the Nextcloud
 * `av_block_unreachable=false` choice (§179): a stopped ClamAV must not halt
 * all document intake. `clamav` is in Paperless's `requires` so the dashboard
 * still warns when it is down.
 *
 * Runs from composeUpWithManagedConfig before `docker compose up`, alongside
 * the other managed-config writers — the fragment and script must exist before
 * the container starts. No-op for every other service and when ClamAV is not
 * part of the deployment (in which case any previously-written fragment/script
 * is removed, so Paperless does not point at a script that is no longer
 * maintained). Never throws.
 */

import fs from 'fs';
import path from 'path';
import { getPublishedUpstreamPort, resolveComposeFile, MANAGED_COMPOSE_FILENAME } from '../config/services';
import { getHostGatewayIp } from '../utils/network';
import logger from '../utils/logger';

const PAPERLESS_SERVICE = 'paperless';
const CLAMAV_SERVICE = 'clamav';
// clamd's own default TCP port inside its container, used if the published
// host port can't be read for some reason.
const CLAMD_DEFAULT_PORT = 3310;

/** The Paperless compose service the fragment extends. */
const PAPERLESS_COMPOSE_SERVICE = 'paperless-ngx';

/**
 * Where the script lands, both sides of the bind mount. `apps/paperless/data/data`
 * → `/usr/src/paperless/data` (PAPERLESS_DATA_DIR): writable, and present on a
 * fresh clone once the reconciler has run.
 */
const SCRIPT_BASENAME = 'pre-consume-clamav.py';
export const PRE_CONSUME_SCRIPT_CONTAINER_PATH = `/usr/src/paperless/data/${SCRIPT_BASENAME}`;

export function preConsumeScriptHostPath(appDir: string): string {
  return path.join(appDir, 'data', 'data', SCRIPT_BASENAME);
}

export function managedComposeFragmentPath(appDir: string): string {
  return path.join(appDir, MANAGED_COMPOSE_FILENAME);
}

export interface PaperlessClamavPlan {
  host: string;
  port: number;
}

/** The clamd host/port, or null when ClamAV isn't in this deployment. */
export async function buildPaperlessClamavPlan(): Promise<PaperlessClamavPlan | null> {
  if (!resolveComposeFile(CLAMAV_SERVICE)?.composeFile) {
    return null;
  }
  return {
    host: await getHostGatewayIp(),
    port: getPublishedUpstreamPort(CLAMAV_SERVICE) ?? CLAMD_DEFAULT_PORT,
  };
}

/**
 * The pre-consume scanner. Rendered per host with clamd's address baked in
 * (the script gets no argv — Paperless passes the document path in
 * `DOCUMENT_WORKING_PATH`). Python 3 is already in the Paperless image.
 */
export function renderPreConsumeScript(host: string, port: number): string {
  return `#!/usr/bin/env python3
# Generated by the Business Lab dashboard (services/paperlessClamav.ts).
# Streams the document Paperless is about to consume to clamd's INSTREAM over
# TCP and rejects it (exit 1 -> ConsumerError) on a FOUND verdict. clamd
# unreachable or erroring -> exit 0 (fail open), matching the Nextcloud
# av_block_unreachable=false choice (plan.md §179): a stopped ClamAV must not
# halt all document intake. Regenerated on every Paperless start.
import os
import socket
import struct
import sys

CLAMD_HOST = ${JSON.stringify(host)}
CLAMD_PORT = ${port}
CHUNK = 8192


def emit(msg):
    print(f"clamav pre-consume: {msg}", file=sys.stderr)


target = os.environ.get("DOCUMENT_WORKING_PATH") or os.environ.get("DOCUMENT_SOURCE_PATH")
if not target or not os.path.isfile(target):
    emit(f"no readable document at {target!r}; letting it through")
    sys.exit(0)

try:
    with socket.create_connection((CLAMD_HOST, CLAMD_PORT), timeout=30) as sock:
        sock.sendall(b"zINSTREAM\\0")
        with open(target, "rb") as handle:
            while True:
                chunk = handle.read(CHUNK)
                if not chunk:
                    break
                sock.sendall(struct.pack("!L", len(chunk)) + chunk)
        sock.sendall(struct.pack("!L", 0))
        sock.settimeout(120)
        reply = b""
        while b"\\0" not in reply:
            buf = sock.recv(4096)
            if not buf:
                break
            reply += buf
except OSError as exc:
    emit(f"clamd unreachable at {CLAMD_HOST}:{CLAMD_PORT} ({exc}); failing open")
    sys.exit(0)

verdict = reply.decode("utf-8", "replace").strip().strip("\\0")
if verdict.endswith("FOUND"):
    emit(f"REJECTED {target} - {verdict}")
    sys.exit(1)
if verdict.endswith("OK"):
    sys.exit(0)
# A real clamd error reply (e.g. INSTREAM size limit exceeded). Log it and
# fail open, same rationale as an unreachable daemon.
emit(f"unexpected clamd reply {verdict!r}; failing open")
sys.exit(0)
`;
}

/**
 * The managed compose fragment: the one env var the base compose file does not
 * carry. Static — clamd's address lives in the script, not here, so this file
 * never churns.
 */
export function renderManagedComposeFragment(): string {
  return `# Generated by the Business Lab dashboard (services/paperlessClamav.ts).
# Adds PAPERLESS_PRE_CONSUME_SCRIPT, which the base docker-compose.yml does not
# reference, so every document is virus-scanned against ClamAV before intake.
# Removed automatically when ClamAV leaves the deployment. Runtime state,
# per-host; docker-compose.yml is the spec.
services:
  ${PAPERLESS_COMPOSE_SERVICE}:
    environment:
      PAPERLESS_PRE_CONSUME_SCRIPT: ${PRE_CONSUME_SCRIPT_CONTAINER_PATH}
`;
}

function removeIfPresent(file: string): void {
  if (fs.existsSync(file)) {
    fs.rmSync(file);
    logger.info('Removed Paperless ClamAV wiring', { file });
  }
}

/**
 * Reconcile Paperless's pre-consume virus scan. No-op for every other service.
 * Never throws — a broken scan hook must not block a Paperless start (the
 * fragment write is what could fail; if it does, Paperless just starts without
 * scanning).
 */
export async function reconcilePaperlessClamav(serviceName: string, appDir: string): Promise<void> {
  if (serviceName !== PAPERLESS_SERVICE) {
    return;
  }
  if (!resolveComposeFile(PAPERLESS_SERVICE)?.composeFile) {
    return;
  }

  const scriptPath = preConsumeScriptHostPath(appDir);
  const fragmentPath = managedComposeFragmentPath(appDir);

  try {
    const plan = await buildPaperlessClamavPlan();
    if (!plan) {
      // ClamAV isn't in this deployment — make sure Paperless isn't left
      // pointing at a script we won't keep current.
      removeIfPresent(fragmentPath);
      removeIfPresent(scriptPath);
      logger.info('Skipping the Paperless/ClamAV wiring: ClamAV is not part of this deployment');
      return;
    }

    fs.mkdirSync(path.dirname(scriptPath), { recursive: true });
    // 0o755: Paperless runs the path directly as argv[0], so it must be
    // executable and carry its own shebang.
    fs.writeFileSync(scriptPath, renderPreConsumeScript(plan.host, plan.port), { mode: 0o755 });
    fs.chmodSync(scriptPath, 0o755);
    fs.writeFileSync(fragmentPath, renderManagedComposeFragment());

    logger.info('Paperless/ClamAV intake scan reconciled', {
      host: plan.host,
      port: plan.port,
      script: scriptPath,
    });
  } catch (error) {
    logger.error('Failed to wire Paperless to ClamAV', { error: (error as Error).message });
  }
}
