/**
 * Samba's `smb.conf` is a managed config file: the dashboard owns the share
 * definition, not a hand-edited file on the host (§0.2). This renders it from
 * the app's .env (share name + the account the entrypoint creates) just
 * before `docker compose up`, the same way applyExposureConfigFiles
 * runs — so the share is correct from the first
 * start with no field for anyone to fill in.
 *
 * dockur/samba's entrypoint uses a bind-mounted /etc/samba/smb.conf verbatim
 * when it exists and is non-empty (it does NOT merge env vars into a custom
 * file), so everything the share needs — path, writability, force user — has
 * to be baked in here. The entrypoint still creates the Unix/Samba account
 * from USER/PASS/UID/GID separately.
 *
 * Multi-user access (§480-style credential fan-out, sambaUserProvisioning.ts)
 * rides the same mechanism dockur/samba already ships for this: a bind-mounted
 * `users.conf` (one `username:UID:groupname:GID:password:homedir` line per
 * account) that its entrypoint loops over on every start, alongside the
 * legacy single USER/PASS account. Every granted dashboard user shares the
 * legacy account's UID/GID/homedir — this grants logins to the one shared
 * folder, not per-person permissions — so `force user`/`force group` in
 * smb.conf stay pinned to that single account regardless of who authenticates;
 * only `valid users` grows to include everyone currently granted, or nobody
 * but the legacy account could actually connect.
 */

import fsSync from 'fs';
import fs from 'fs/promises';
import path from 'path';
import logger from '../utils/logger';
import { parseEnvFile } from '../utils/envFile';
import { query } from '../utils/database';

export const SAMBA_SERVICE = 'samba';

// Must match the container path the compose file bind-mounts the share to.
// dockur/samba's entrypoint picks /storage over its default /shared when that
// directory exists (a bind mount always creates it), so this is the path it
// will chown and treat as the account's home.
const SHARE_PATH = '/storage';

export interface SambaSettings {
  shareName: string;
  user: string;
}

// A name with a space or a `]` would break the section header or the account;
// fall back to the default rather than emit a broken file.
const SAFE = /^[A-Za-z0-9._-]+$/;

export function resolveSambaSettings(env: Record<string, string>): SambaSettings {
  const rawName = (env.SAMBA_SHARE_NAME ?? '').trim();
  const rawUser = (env.SAMBA_USER ?? '').trim();
  return {
    shareName: SAFE.test(rawName) ? rawName : 'share',
    user: SAFE.test(rawUser) ? rawUser : 'labshare',
  };
}

export function buildSmbConf({ shareName, user, validUsers }: SambaSettings & { validUsers?: string[] }): string {
  // `force user`/`force group` make every file in the share owned by the one
  // account regardless of who connected — this is a shared-folder LAN share,
  // not per-user permissions. `smb` is the group dockur/samba puts every
  // account in. `valid users` is the actual access gate: it defaults to just
  // the legacy account, but grows to include every dashboard-granted samba
  // user (sambaUserProvisioning.ts) — otherwise a granted user's account
  // could exist in the passdb and still never be allowed to connect.
  const validUsersLine = (validUsers?.length ? validUsers : [user]).join(' ');
  return `# Generated by the dashboard (backend/src/services/sambaConfig.ts) on every
# start of the Samba app. Do not edit by hand — changes are overwritten.
[global]
   workgroup = WORKGROUP
   server string = %h
   security = user
   map to guest = never
   server min protocol = SMB2
   load printers = no
   printing = bsd
   printcap name = /dev/null
   disable spoolss = yes
   unix charset = UTF-8
   dos charset = CP850

[${shareName}]
   path = ${SHARE_PATH}
   comment = ${shareName}
   browseable = yes
   read only = no
   writable = yes
   valid users = ${validUsersLine}
   force user = ${user}
   force group = smb
   create mask = 0664
   directory mask = 0775
`;
}

export interface SambaUsersConfEntry {
  username: string;
  password: string;
}

export interface SambaUsersConfShared {
  uid: string;
  gid: string;
  group: string;
  homedir: string;
}

/**
 * Renders dockur/samba's `users.conf` (readme.md: "How do I configure
 * multiple users?"). Every entry shares the same UID/GID/homedir — see the
 * module doc comment — only username and password vary per line. A `*`
 * password tells dockur/samba's own entrypoint to leave that account's
 * existing password alone (its `set_password`/`CLEAR` check treats `*`/`!`
 * as "no value"), which is how a full re-render can cover every granted user
 * without the dashboard ever holding onto more than one plaintext password
 * at a time — see sambaUserProvisioning.ts.
 */
export function buildUsersConf(entries: SambaUsersConfEntry[], shared: SambaUsersConfShared): string {
  const header = `# Generated by the dashboard (backend/src/services/sambaConfig.ts) on every
# start of the Samba app, and whenever a dashboard user is granted or denied
# Samba access. Do not edit by hand — changes are overwritten.
# username:UID:groupname:GID:password:homedir
`;
  const lines = entries.map(
    (entry) => `${entry.username}:${shared.uid}:${shared.group}:${shared.gid}:${entry.password}:${shared.homedir}`
  );
  return header + lines.join('\n') + (lines.length ? '\n' : '');
}

// dockur/samba's own `adduser -S` (BusyBox) rejects '@', '.', and uppercase —
// none of which a dashboard username (Joi: 3-64 chars, [a-zA-Z0-9_.@-]) is
// guaranteed to avoid — so this derives a Samba-safe handle instead of using
// it verbatim.
export function sambaUsernameFor(dashboardUsername: string): string {
  const base = dashboardUsername
    .toLowerCase()
    .replace(/[^a-z0-9_-]/g, '-')
    .replace(/^-+/, '')
    .slice(0, 32);
  return base || 'user';
}

/**
 * Maps every currently-granted dashboard user to a Samba-safe, collision-free
 * username, in a stable order (ascending user id) so re-derivation is
 * deterministic. ponytail: a collision falls back to `<name>-<id>`, not
 * re-checked against further collisions — fine for a homelab's handful of
 * accounts, revisit if this list ever grows large enough for that to bite.
 */
export function resolveGrantedSambaUsernames(users: { id: number; username: string }[]): Map<number, string> {
  const taken = new Set<string>();
  const result = new Map<number, string>();
  for (const user of users) {
    let candidate = sambaUsernameFor(user.username);
    if (taken.has(candidate)) {
      candidate = `${candidate.slice(0, 26)}-${user.id}`;
    }
    taken.add(candidate);
    result.set(user.id, candidate);
  }
  return result;
}

/**
 * Every dashboard account currently granted Samba access, ascending by id.
 * A plain `query()` against `user_app_access`/`users` rather than a call
 * into userAppAccess.ts — that module imports noSsoCredentialFanout.ts,
 * which imports sambaUserProvisioning.ts, which imports executor.ts for
 * `restartService`, which imports this file for `applySambaConfig`. Calling
 * back into userAppAccess.ts from here would close that loop.
 */
async function getGrantedSambaUsers(): Promise<{ id: number; username: string }[]> {
  const result = await query<{ id: number; username: string }>(
    `SELECT u.id, u.username FROM user_app_access a
     JOIN users u ON u.id = a.user_id
     WHERE a.service_name = $1
     ORDER BY u.id ASC`,
    [SAMBA_SERVICE]
  );
  return result.rows;
}

/**
 * Rewrites both `smb.conf` and `users.conf` from the current
 * `user_app_access` grants. `override` supplies the one plaintext password
 * this call actually has in hand (a grant, a password reset, the next-login
 * catch-up) — every other already-granted user's line gets `*` instead, so
 * the dashboard never needs to retain anyone else's plaintext to re-render
 * this file. Returns the id → Samba-username map so the caller (
 * sambaUserProvisioning.ts) knows which account it just wrote.
 */
export async function regenerateSambaFiles(
  appDir: string,
  override?: { userId: number; password: string }
): Promise<Map<number, string>> {
  const granted = await getGrantedSambaUsers();
  const usernames = resolveGrantedSambaUsernames(granted);

  const envPath = path.join(appDir, '.env');
  const env = fsSync.existsSync(envPath) ? parseEnvFile(envPath) : {};
  const settings = resolveSambaSettings(env);
  const uid = (env.SAMBA_UID ?? '').trim() || '1000';
  const gid = (env.SAMBA_GID ?? '').trim() || '1000';

  const entries: SambaUsersConfEntry[] = granted.map((user) => ({
    username: usernames.get(user.id)!,
    password: override?.userId === user.id ? override.password : '*',
  }));

  const dataDir = path.join(appDir, 'data');
  await fs.writeFile(
    path.join(dataDir, 'users.conf'),
    buildUsersConf(entries, { uid, gid, group: 'smb', homedir: SHARE_PATH }),
    'utf8'
  );
  await fs.writeFile(
    path.join(dataDir, 'smb.conf'),
    buildSmbConf({ ...settings, validUsers: [settings.user, ...entries.map((entry) => entry.username)] }),
    'utf8'
  );

  return usernames;
}

/**
 * Write apps/samba/data/{smb.conf,users.conf}. Unlike most rendered config
 * this is not best-effort: if either file is missing when `compose up` runs,
 * Docker creates the bind source as a directory and dockur/samba's
 * entrypoint aborts. So a failure here should fail the start rather than
 * leave a broken bind.
 */
export async function applySambaConfig(serviceName: string, appDir: string): Promise<void> {
  if (serviceName !== SAMBA_SERVICE) {
    return;
  }

  const dataDir = path.join(appDir, 'data');
  await fs.mkdir(path.join(dataDir, 'share'), { recursive: true });

  await regenerateSambaFiles(appDir);
  logger.info('Wrote the Samba share config');
}
