import { describe, expect, it } from 'vitest';

import { buildSmbConf, resolveSambaSettings } from './sambaConfig';

describe('resolveSambaSettings', () => {
  it('takes the share name and user from the env', () => {
    expect(resolveSambaSettings({ SAMBA_SHARE_NAME: 'office', SAMBA_USER: 'staff' })).toEqual({
      shareName: 'office',
      user: 'staff',
    });
  });

  it('falls back to defaults when the env is empty', () => {
    expect(resolveSambaSettings({})).toEqual({ shareName: 'share', user: 'labshare' });
  });

  it('rejects a value that would break the config and uses the default instead', () => {
    // A space or `]` in the section header produces a smb.conf smbd refuses
    // to load — silently, on next start.
    expect(resolveSambaSettings({ SAMBA_SHARE_NAME: 'my share]', SAMBA_USER: 'a b' })).toEqual({
      shareName: 'share',
      user: 'labshare',
    });
  });
});

describe('buildSmbConf', () => {
  it('emits one share section named after the share, forced to the account', () => {
    const conf = buildSmbConf({ shareName: 'office', user: 'staff' });
    expect(conf).toContain('[office]');
    expect(conf).toContain('path = /storage');
    expect(conf).toContain('valid users = staff');
    expect(conf).toContain('force user = staff');
    expect(conf).toContain('read only = no');
  });

  it('carries a do-not-edit banner — the file is regenerated on every start', () => {
    expect(buildSmbConf({ shareName: 'share', user: 'labshare' })).toMatch(/^# Generated by the dashboard/);
  });

  it('pins a modern SMB minimum and turns off guest access', () => {
    const conf = buildSmbConf({ shareName: 'share', user: 'labshare' });
    expect(conf).toContain('server min protocol = SMB2');
    expect(conf).toContain('map to guest = never');
  });
});
