import { describe, expect, it } from 'vitest';

import {
  buildSambaUserEntries,
  buildSmbConf,
  buildUsersConf,
  GRANTED_UID_BASE,
  resolveGrantedSambaUsernames,
  resolveSambaSettings,
  sambaUsernameFor,
} from './sambaConfig';

describe('resolveSambaSettings', () => {
  it('takes the share name and user from the env', () => {
    expect(resolveSambaSettings({ SAMBA_SHARE_NAME: 'office', SAMBA_USER: 'staff' })).toEqual({
      shareName: 'office',
      user: 'staff',
    });
  });

  it('falls back to defaults when the env is empty', () => {
    expect(resolveSambaSettings({})).toEqual({ shareName: 'share', user: 'labshare' });
  });

  it('rejects a value that would break the config and uses the default instead', () => {
    // A space or `]` in the section header produces a smb.conf smbd refuses
    // to load — silently, on next start.
    expect(resolveSambaSettings({ SAMBA_SHARE_NAME: 'my share]', SAMBA_USER: 'a b' })).toEqual({
      shareName: 'share',
      user: 'labshare',
    });
  });
});

describe('buildSmbConf', () => {
  it('emits one share section named after the share, forced to the account', () => {
    const conf = buildSmbConf({ shareName: 'office', user: 'staff' });
    expect(conf).toContain('[office]');
    expect(conf).toContain('path = /storage');
    expect(conf).toContain('valid users = staff');
    expect(conf).toContain('force user = staff');
    expect(conf).toContain('read only = no');
  });

  it('carries a do-not-edit banner — the file is regenerated on every start', () => {
    expect(buildSmbConf({ shareName: 'share', user: 'labshare' })).toMatch(/^# Generated by the dashboard/);
  });

  it('pins a modern SMB minimum and turns off guest access', () => {
    const conf = buildSmbConf({ shareName: 'share', user: 'labshare' });
    expect(conf).toContain('server min protocol = SMB2');
    expect(conf).toContain('map to guest = never');
  });

  it('defaults valid users to just the legacy account when no one else is granted', () => {
    const conf = buildSmbConf({ shareName: 'share', user: 'labshare' });
    expect(conf).toContain('valid users = labshare');
  });

  it('lists every granted user in valid users, but keeps force user/group on the legacy account', () => {
    const conf = buildSmbConf({ shareName: 'share', user: 'labshare', validUsers: ['labshare', 'bob', 'alice'] });
    expect(conf).toContain('valid users = labshare bob alice');
    expect(conf).toContain('force user = labshare');
    expect(conf).toContain('force group = smb');
  });
});

describe('sambaUsernameFor', () => {
  it('lowercases and strips characters BusyBox adduser rejects', () => {
    expect(sambaUsernameFor('Bob.Smith@example.com')).toBe('bob-smith-example-com');
  });

  it('falls back to a placeholder when nothing safe survives', () => {
    expect(sambaUsernameFor('@@@')).toBe('user');
  });

  it('truncates to 32 characters', () => {
    const long = 'a'.repeat(50);
    expect(sambaUsernameFor(long)).toHaveLength(32);
  });
});

describe('resolveGrantedSambaUsernames', () => {
  it('maps each user to a sanitized, stable username', () => {
    const result = resolveGrantedSambaUsernames([
      { id: 1, username: 'bob' },
      { id: 2, username: 'alice' },
    ]);
    expect(result).toEqual(
      new Map([
        [1, 'bob'],
        [2, 'alice'],
      ])
    );
  });

  it('disambiguates a collision by suffixing the dashboard user id', () => {
    const result = resolveGrantedSambaUsernames([
      { id: 1, username: 'bob' },
      { id: 2, username: 'Bob' },
    ]);
    expect(result.get(1)).toBe('bob');
    expect(result.get(2)).toBe('bob-2');
  });
});

describe('buildSambaUserEntries', () => {
  it('always puts the legacy account first, even with nobody granted', () => {
    const entries = buildSambaUserEntries({ username: 'labshare', uid: '1000', password: 'legacy-pw' }, [], new Map());
    expect(entries).toEqual([{ username: 'labshare', uid: '1000', password: 'legacy-pw' }]);
  });

  it('appends every granted user with * unless they are the override, each on their own UID', () => {
    const usernames = new Map([
      [1, 'bob'],
      [2, 'alice'],
    ]);
    const entries = buildSambaUserEntries(
      { username: 'labshare', uid: '1000', password: 'legacy-pw' },
      [
        { id: 1, username: 'Bob' },
        { id: 2, username: 'Alice' },
      ],
      usernames,
      { userId: 2, password: 'fresh-pw' }
    );
    expect(entries).toEqual([
      { username: 'labshare', uid: '1000', password: 'legacy-pw' },
      { username: 'bob', uid: String(GRANTED_UID_BASE + 1), password: '*' },
      { username: 'alice', uid: String(GRANTED_UID_BASE + 2), password: 'fresh-pw' },
    ]);
  });

  it('never gives a granted user the legacy account\'s own UID', () => {
    // Regression: BusyBox `adduser` has no way to create a second account on
    // a UID already in use — reusing the legacy UID crash-loops the
    // container (plan.md §742.3).
    const entries = buildSambaUserEntries(
      { username: 'labshare', uid: '1000', password: 'legacy-pw' },
      [{ id: 1, username: 'bob' }],
      new Map([[1, 'bob']])
    );
    expect(entries[1].uid).not.toBe('1000');
  });

  it('never rewrites the legacy account\'s password just because someone else was granted', () => {
    // Regression: this account must never come back as '*' — it isn't
    // subject to the same "leave alone unless overridden" rule granted
    // users are, its real password always comes straight from .env.
    const entries = buildSambaUserEntries(
      { username: 'labshare', uid: '1000', password: 'legacy-pw' },
      [{ id: 1, username: 'bob' }],
      new Map([[1, 'bob']]),
      { userId: 1, password: 'bobs-fresh-pw' }
    );
    expect(entries[0]).toEqual({ username: 'labshare', uid: '1000', password: 'legacy-pw' });
  });
});

describe('buildUsersConf', () => {
  it('renders one username:UID:groupname:GID:password:homedir line per entry, each keeping its own UID', () => {
    const conf = buildUsersConf(
      [
        { username: 'bob', uid: '30001', password: 'secret' },
        { username: 'alice', uid: '30002', password: '*' },
      ],
      { gid: '1000', group: 'smb', homedir: '/storage' }
    );
    expect(conf).toContain('bob:30001:smb:1000:secret:/storage');
    expect(conf).toContain('alice:30002:smb:1000:*:/storage');
  });

  it('renders just the header with no entries', () => {
    const conf = buildUsersConf([], { gid: '1000', group: 'smb', homedir: '/storage' });
    expect(conf).toContain('username:UID:groupname:GID:password:homedir');
    expect(conf).not.toContain(':1000:');
  });
});
