/**
 * Samba's `smb.conf` is a managed config file: the dashboard owns the share
 * definition, not a hand-edited file on the host (§0.2). This renders it from
 * the app's .env (share name + the account the entrypoint creates) just
 * before `docker compose up`, the same way applyKitchenConfig and
 * applyExposureConfigFiles run — so the share is correct from the first
 * start with no field for anyone to fill in.
 *
 * dockur/samba's entrypoint uses a bind-mounted /etc/samba/smb.conf verbatim
 * when it exists and is non-empty (it does NOT merge env vars into a custom
 * file), so everything the share needs — path, writability, force user — has
 * to be baked in here. The entrypoint still creates the Unix/Samba account
 * from USER/PASS/UID/GID separately.
 */

import fsSync from 'fs';
import fs from 'fs/promises';
import path from 'path';
import logger from '../utils/logger';
import { parseEnvFile } from '../utils/envFile';

export const SAMBA_SERVICE = 'samba';

// Must match the container path the compose file bind-mounts the share to.
// dockur/samba's entrypoint picks /storage over its default /shared when that
// directory exists (a bind mount always creates it), so this is the path it
// will chown and treat as the account's home.
const SHARE_PATH = '/storage';

export interface SambaSettings {
  shareName: string;
  user: string;
}

// A name with a space or a `]` would break the section header or the account;
// fall back to the default rather than emit a broken file.
const SAFE = /^[A-Za-z0-9._-]+$/;

export function resolveSambaSettings(env: Record<string, string>): SambaSettings {
  const rawName = (env.SAMBA_SHARE_NAME ?? '').trim();
  const rawUser = (env.SAMBA_USER ?? '').trim();
  return {
    shareName: SAFE.test(rawName) ? rawName : 'share',
    user: SAFE.test(rawUser) ? rawUser : 'labshare',
  };
}

export function buildSmbConf({ shareName, user }: SambaSettings): string {
  // `force user`/`force group` make every file in the share owned by the one
  // account regardless of who connected — this is a single-user LAN share,
  // not a multi-tenant server. `smb` is the group dockur/samba puts the user
  // in. `valid users` keeps it to that account even though the port is
  // LAN-only.
  return `# Generated by the dashboard (backend/src/services/sambaConfig.ts) on every
# start of the Samba app. Do not edit by hand — changes are overwritten.
[global]
   workgroup = WORKGROUP
   server string = %h
   security = user
   map to guest = never
   server min protocol = SMB2
   load printers = no
   printing = bsd
   printcap name = /dev/null
   disable spoolss = yes
   unix charset = UTF-8
   dos charset = CP850

[${shareName}]
   path = ${SHARE_PATH}
   comment = ${shareName}
   browseable = yes
   read only = no
   writable = yes
   valid users = ${user}
   force user = ${user}
   force group = smb
   create mask = 0664
   directory mask = 0775
`;
}

/**
 * Write apps/samba/data/smb.conf. Not best-effort like the Kitchen config: if
 * this file is missing when `compose up` runs, Docker creates the bind source
 * as a directory and dockur/samba's entrypoint aborts. So a failure here
 * should fail the start rather than leave a broken bind.
 */
export async function applySambaConfig(serviceName: string, appDir: string): Promise<void> {
  if (serviceName !== SAMBA_SERVICE) {
    return;
  }

  const dataDir = path.join(appDir, 'data');
  await fs.mkdir(path.join(dataDir, 'share'), { recursive: true });

  const envPath = path.join(appDir, '.env');
  // ensureGeneratedSecrets writes .env before this runs; fall back to
  // defaults if a fresh clone somehow reaches here without one.
  const env = fsSync.existsSync(envPath) ? parseEnvFile(envPath) : {};

  const settings = resolveSambaSettings(env);
  await fs.writeFile(path.join(dataDir, 'smb.conf'), buildSmbConf(settings), 'utf8');
  logger.info('Wrote the Samba share config', { share: settings.shareName });
}
