import { describe, expect, it } from 'vitest';

import { renderWebdavConfig } from './webdavConfig';

describe('renderWebdavConfig', () => {
  it('embeds the username and password as single-quoted YAML scalars', () => {
    const conf = renderWebdavConfig('admin', 's3cret', false);
    expect(conf).toContain("username: 'admin'");
    expect(conf).toContain("password: 's3cret'");
  });

  it('escapes an embedded single quote so the YAML stays valid', () => {
    const conf = renderWebdavConfig("o'brien", "p'word", false);
    expect(conf).toContain("username: 'o''brien'");
    expect(conf).toContain("password: 'p''word'");
  });

  it('flips behindProxy with exposure state', () => {
    expect(renderWebdavConfig('admin', 'x', true)).toContain('behindProxy: true');
    expect(renderWebdavConfig('admin', 'x', false)).toContain('behindProxy: false');
  });

  it('grants full read/write/delete — the one account is a native backup client, not a browsing user', () => {
    expect(renderWebdavConfig('admin', 'x', false)).toContain('permissions: CRUD');
  });

  it('carries a do-not-edit banner — the file is regenerated on every start', () => {
    expect(renderWebdavConfig('admin', 'x', false)).toMatch(/^# Generated by the dashboard/);
  });
});
