/**
 * hacdias/webdav takes its whole configuration — address, users, permissions —
 * from a mounted config.yml; its image is `FROM scratch` (no shell, so no
 * entrypoint script could template env vars into a file even if the app
 * supported that). So the dashboard owns this file outright and rewrites it
 * before every start, the same pattern as Samba's smb.conf
 * (services/sambaConfig.ts) and Vikunja's managed config.yml
 * (services/vikunjaConfig.ts).
 *
 * Unlike Vikunja's file (only written while exposed, for an optional OIDC
 * button), this one is load-bearing from the first start — with no config.yml
 * the container has no users and nothing answers Basic Auth at all — so it is
 * written unconditionally once WEBDAV_PASSWORD exists. `behindProxy` still
 * follows exposure state, the same as ntfy's NTFY_BEHIND_PROXY.
 */

import fs from 'fs';
import path from 'path';
import logger from '../utils/logger';
import { parseEnvFile } from '../utils/envFile';
import { getServiceExposureRow } from './exposure';

export const WEBDAV_SERVICE = 'webdav';

// Hand-rendered YAML, not a library: every value here is either a controlled
// boolean or a single scalar wrapped in a single-quoted YAML string, whose
// only escape rule is doubling an embedded quote.
function yamlQuote(value: string): string {
  return `'${value.replace(/'/g, "''")}'`;
}

export function webdavConfigPath(appDir: string): string {
  return path.join(appDir, 'data', 'config.yml');
}

export function renderWebdavConfig(username: string, password: string, behindProxy: boolean): string {
  return [
    '# Generated by the dashboard (backend/src/services/webdavConfig.ts) on',
    '# every start of the WebDAV app. Do not edit by hand — changes are',
    '# overwritten. Change the username/password from the app config panel.',
    'address: 0.0.0.0',
    'port: 6065',
    `behindProxy: ${behindProxy}`,
    'directory: /data',
    'permissions: CRUD',
    'users:',
    `  - username: ${yamlQuote(username)}`,
    `    password: ${yamlQuote(password)}`,
    '',
  ].join('\n');
}

/**
 * Write data/config.yml before `compose up`. No-op for every other service,
 * and a no-op (with a log line) until WEBDAV_PASSWORD has been generated —
 * ensureGeneratedSecrets runs earlier in the same start and fills it from
 * WEBDAV_SERVICE's autoGeneratedSecrets, so this only stays empty on a
 * config panel that has never been saved.
 */
export async function applyWebdavConfig(serviceName: string, appDir: string): Promise<void> {
  if (serviceName !== WEBDAV_SERVICE) {
    return;
  }

  try {
    const dataDir = path.join(appDir, 'data');
    fs.mkdirSync(path.join(dataDir, 'files'), { recursive: true });

    const envPath = path.join(appDir, '.env');
    const env = fs.existsSync(envPath) ? parseEnvFile(envPath) : {};
    const username = (env.WEBDAV_USERNAME ?? '').trim() || 'admin';
    const password = env.WEBDAV_PASSWORD ?? '';
    if (!password) {
      logger.warn('webdav config.yml not written: WEBDAV_PASSWORD is unset — save its config panel once to generate it');
      return;
    }

    const exposureRow = await getServiceExposureRow(WEBDAV_SERVICE);
    const behindProxy = Boolean(exposureRow?.enabled);

    const configPath = webdavConfigPath(appDir);
    const next = renderWebdavConfig(username, password, behindProxy);
    if (!fs.existsSync(configPath) || fs.readFileSync(configPath, 'utf8') !== next) {
      fs.writeFileSync(configPath, next, { mode: 0o644 });
      logger.info('Wrote managed webdav config.yml');
    }
  } catch (error) {
    logger.error('Failed to apply webdav config.yml', { error: (error as Error).message });
  }
}
