#!/usr/bin/env bash
# Regenerate plan-index.md, a navigation aid for plan.md.
#
#   ./scripts/plan-index.sh
#
# plan.md is the project's memory and is deliberately append-only — the record
# of what was tried and rejected is the point, and summarising it away would
# throw out the half that has repeatedly turned out to matter. But at ~10,000
# lines and ~90 sections, *finding* a section meant grepping for it every time.
#
# So the index is a separate generated file rather than a header inside
# plan.md: it cannot rewrite history by accident, and the line numbers it
# prints stay correct because inserting it does not move anything.
set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/.."

TOTAL=$(wc -l < plan.md)

{
  echo "# plan.md index"
  echo
  echo "Generated by \`scripts/plan-index.sh\`. Do not edit by hand — regenerate it"
  echo "after appending a section."
  echo
  echo "\`plan.md\` is ${TOTAL} lines and is meant to be read a section at a time, never"
  echo "whole. Find the section here, then read exactly its range:"
  echo
  echo '```bash'
  echo 'sed -n "8437,8557p" plan.md'
  echo '```'
  echo
  echo "Sections appear in **file order, which is not always numeric order** — work"
  echo "appended later can carry an earlier number when it closes out an earlier plan."
  echo
  echo "| Range | Section |"
  echo "|---|---|"
  grep -n '^## ' plan.md | awk -F':## ' -v total="$TOTAL" '
    { line[NR] = $1; title[NR] = $2 }
    END {
      for (i = 1; i <= NR; i++) {
        end = (i < NR) ? line[i + 1] - 1 : total
        t = title[i]
        gsub(/\|/, "\\|", t)
        printf "| `%s,%sp` | %s |\n", line[i], end, t
      }
    }'
} > plan-index.md

echo "plan-index.md: $(grep -c '^| .' plan-index.md) sections, plan.md is ${TOTAL} lines"
