#!/bin/sh
# Kopia has no "create the repository if it is missing" start mode: `kopia
# server start` refuses to run until a repository is connected. This wrapper
# connects to the repository (filesystem under /repository, or an s3 bucket
# — plan.md §221), creating it on the very first start, so the app
# auto-configures with nothing typed (§0.3).
#
# KOPIA_PASSWORD (repository encryption) and the two server credential pairs
# are generated by the dashboard — see .env.example. The image sets
# KOPIA_PERSIST_CREDENTIALS_ON_CONNECT=false, so KOPIA_PASSWORD is never
# written to the config volume and must be present in the environment on
# every start; that is what `.env` is for.
set -e

REPO_PATH=/repository

if [ "${BACKUP_REPO_KIND:-filesystem}" = "s3" ]; then
  # `set --` builds the positional-args list so the optional --endpoint flag
  # and the raw BACKUP_S3_EXTRA_ARGS passthrough can each disappear entirely
  # when unset, rather than needing string concatenation. BACKUP_S3_EXTRA_ARGS
  # is deliberately unquoted — same "escape hatch, appended verbatim, word
  # split" contract the SMB/NFS mount options field already has.
  set -- s3 \
    --bucket="$BACKUP_S3_BUCKET" \
    --access-key="$BACKUP_S3_ACCESS_KEY_ID" \
    --secret-access-key="$BACKUP_S3_SECRET_ACCESS_KEY" \
    ${BACKUP_S3_ENDPOINT:+--endpoint="$BACKUP_S3_ENDPOINT"} \
    $BACKUP_S3_EXTRA_ARGS
  LABEL="s3://$BACKUP_S3_BUCKET"
else
  set -- filesystem --path="$REPO_PATH"
  LABEL="$REPO_PATH"
fi

if kopia repository connect "$@" >/dev/null 2>&1; then
  echo "kopia: connected to existing repository at $LABEL"
else
  echo "kopia: no repository at $LABEL yet — creating one"
  kopia repository create "$@"
fi

# A sane default retention ladder for the global policy, so a snapshot taken
# from the UI before slice 2's kopiaClient.ts manages per-source policy is not
# kept forever. Best-effort: a repo that already carries a policy is left as-is.
kopia policy set --global \
  --keep-latest 10 --keep-hourly 24 --keep-daily 14 \
  --keep-weekly 8 --keep-monthly 6 --keep-annual 2 || true

# --insecure: plain HTTP behind basic auth. LAN-direct traffic never reaches
# NPM/Authelia (§93), so the server credentials are the gate. Exposure (TLS
# at the tunnel) is a later slice.
exec kopia server start \
  --address="http://0.0.0.0:51515" \
  --insecure \
  --ui \
  --server-username="$KOPIA_SERVER_USERNAME" \
  --server-password="$KOPIA_SERVER_PASSWORD" \
  --server-control-username="$KOPIA_SERVER_USERNAME" \
  --server-control-password="$KOPIA_SERVER_CONTROL_PASSWORD" \
  --shutdown-grace-period=5s
