#!/bin/sh
# Kopia has no "create the repository if it is missing" start mode: `kopia
# server start` refuses to run until a repository is connected. This wrapper
# connects to the repository (filesystem under /repository, an s3 bucket —
# plan.md §221, or an FTP server via the bundled rclone — plan.md §267),
# creating it on the very first start, so the app auto-configures with
# nothing typed (§0.3).
#
# KOPIA_PASSWORD (repository encryption) and the two server credential pairs
# are generated by the dashboard — see .env.example. The image sets
# KOPIA_PERSIST_CREDENTIALS_ON_CONNECT=false, so KOPIA_PASSWORD is never
# written to the config volume and must be present in the environment on
# every start; that is what `.env` is for.
set -e

REPO_PATH=/repository

if [ "${BACKUP_REPO_KIND:-filesystem}" = "s3" ]; then
  # `set --` builds the positional-args list so the optional --endpoint flag
  # and the raw BACKUP_S3_EXTRA_ARGS passthrough can each disappear entirely
  # when unset, rather than needing string concatenation. BACKUP_S3_EXTRA_ARGS
  # is deliberately unquoted — same "escape hatch, appended verbatim, word
  # split" contract the SMB/NFS mount options field already has.
  set -- s3 \
    --bucket="$BACKUP_S3_BUCKET" \
    --access-key="$BACKUP_S3_ACCESS_KEY_ID" \
    --secret-access-key="$BACKUP_S3_SECRET_ACCESS_KEY" \
    ${BACKUP_S3_ENDPOINT:+--endpoint="$BACKUP_S3_ENDPOINT"} \
    $BACKUP_S3_EXTRA_ARGS
  LABEL="s3://$BACKUP_S3_BUCKET"
elif [ "${BACKUP_REPO_KIND:-filesystem}" = "rclone" ]; then
  # Kopia has no plain-FTP backend; it drives the rclone bundled in this image
  # instead. Build an rclone "backup" remote of type=ftp from the env the
  # dashboard writes (services/kopiaTargetApply.ts), password obscured as
  # rclone.conf requires. --config is passed explicitly so nothing depends on
  # $HOME. BACKUP_RCLONE_EXTRA_ARGS is unquoted — same word-split escape-hatch
  # contract as the s3/mount options fields.
  RCLONE_CONF=/app/config/rclone.conf
  {
    echo "[backup]"
    echo "type = ftp"
    echo "host = $BACKUP_RCLONE_HOST"
    echo "user = $BACKUP_RCLONE_USER"
    echo "pass = $(rclone obscure "$BACKUP_RCLONE_PASS")"
    [ -n "$BACKUP_RCLONE_PORT" ] && echo "port = $BACKUP_RCLONE_PORT"
    [ "$BACKUP_RCLONE_TLS" = "true" ] && echo "explicit_tls = true"
    # Cap simultaneous FTP control connections. Kopia's repository layer opens
    # several blob writes in parallel and each becomes an FTP connection
    # through the rclone bridge; most FTP servers (and every consumer NAS)
    # cap connections per user and just stall the rest, which reads as a hung
    # `repository create`. 4 is well under any real limit and still parallel.
    echo "concurrency = 4"
  } > "$RCLONE_CONF"
  # Kopia's rclone backend takes one `remote:path` string; "/" is the FTP root.
  REMOTE_DIR=$(printf '%s' "${BACKUP_RCLONE_REMOTE_PATH:-/}" | sed 's#^/*##')
  # --vfs-cache-mode=writes: Kopia's rclone backend runs `rclone serve webdav`
  # and speaks WebDAV to it; without a write cache every WebDAV PUT is a
  # synchronous FTP round trip and large blob writes crawl or time out.
  set -- rclone --remote-path="backup:$REMOTE_DIR" \
    --rclone-args="--config=$RCLONE_CONF" \
    --rclone-args=--vfs-cache-mode=writes \
    $BACKUP_RCLONE_EXTRA_ARGS
  LABEL="ftp://$BACKUP_RCLONE_HOST/$REMOTE_DIR"
else
  set -- filesystem --path="$REPO_PATH"
  LABEL="$REPO_PATH"
fi

if kopia repository connect "$@" >/dev/null 2>&1; then
  echo "kopia: connected to existing repository at $LABEL"
else
  echo "kopia: no repository at $LABEL yet — creating one"
  kopia repository create "$@"
fi

# A sane default retention ladder for the global policy, so a snapshot taken
# from the UI before slice 2's kopiaClient.ts manages per-source policy is not
# kept forever. Best-effort: a repo that already carries a policy is left as-is.
kopia policy set --global \
  --keep-latest 10 --keep-hourly 24 --keep-daily 14 \
  --keep-weekly 8 --keep-monthly 6 --keep-annual 2 || true

# --insecure: plain HTTP behind basic auth. LAN-direct traffic never reaches
# NPM/Authelia (§93), so the server credentials are the gate. Exposure (TLS
# at the tunnel) is a later slice.
exec kopia server start \
  --address="http://0.0.0.0:51515" \
  --insecure \
  --ui \
  --server-username="$KOPIA_SERVER_USERNAME" \
  --server-password="$KOPIA_SERVER_PASSWORD" \
  --server-control-username="$KOPIA_SERVER_USERNAME" \
  --server-control-password="$KOPIA_SERVER_CONTROL_PASSWORD" \
  --shutdown-grace-period=5s
